//
// This is a generated file, do not edit!
// Generated by UIResource service, see http://dc-design.intra.xiaojukeji.com/
//

import UIKit

/**
 * @brief 动态图标 SVG Image API
 *
 * $Key: 图标在资源库中Key值，也是业务调用唯一标识符；
 * $Color: 图标内填充颜色，若传入的为 dynamic color 将自动适配深色模式，不传则采用默认 common_icon2_color ;（注意：仅对单色图标生效 ！）
 * $Size: 图标的大小尺寸，若不传则采用SVG 中 viewBox 的默认宽高；
 *
 * For example:
 *  单色图标 —— static func $Key(color: $Color, size: $Size) -> UIImage?
 *  多色图标 —— static func $Key(size: $Size) -> UIImage?
 */

// MARK: - Image.Resource
extension Theme.image.Resource {
    
    /// SVG Image `icon_single_im_label`.
    static let icon_single_im_label = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_label")
    /// SVG Image `icon_single_tab_knowledge`.
    static let icon_single_tab_knowledge = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_tab_knowledge")
    /// SVG Image `icon_single_tab_cloud`.
    static let icon_single_tab_cloud = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_tab_cloud")
    /// SVG Image `icon_single_store`.
    static let icon_single_store = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_store")
    /// SVG Image `icon_single_tab_todo_select`.
    static let icon_single_tab_todo_select = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_tab_todo_select")
    /// SVG Image `icon_single_tab_work`.
    static let icon_single_tab_work = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_tab_work")
    /// SVG Image `icon_single_tab_collect`.
    static let icon_single_tab_collect = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_tab_collect")
    /// SVG Image `icon_single_tab_dialogue`.
    static let icon_single_tab_dialogue = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_tab_dialogue")
    /// SVG Image `icon_single_file`.
    static let icon_single_file = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_file")
    /// SVG Image `icon_single_vpn`.
    static let icon_single_vpn = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_vpn")
    /// SVG Image `icon_single_createmeeting`.
    static let icon_single_createmeeting = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_createmeeting")
    /// SVG Image `icon_single_card`.
    static let icon_single_card = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_card")
    /// SVG Image `icon_single_talking`.
    static let icon_single_talking = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_talking")
    /// SVG Image `icon_single_pay`.
    static let icon_single_pay = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_pay")
    /// SVG Image `icon_single_nomessage`.
    static let icon_single_nomessage = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_nomessage")
    /// SVG Image `icon_single_scan`.
    static let icon_single_scan = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_scan")
    /// SVG Image `icon_single_tab_todo`.
    static let icon_single_tab_todo = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_tab_todo")
    /// SVG Image `icon_single_tab_dialogue_select`.
    static let icon_single_tab_dialogue_select = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_tab_dialogue_select")
    /// SVG Image `icon_single_tab_more`.
    static let icon_single_tab_more = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_tab_more")
    /// SVG Image `icon_single_tab_moreselect`.
    static let icon_single_tab_moreselect = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_tab_moreselect")
    /// SVG Image `icon_single_tab_workselect`.
    static let icon_single_tab_workselect = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_tab_workselect")
    /// SVG Image `icon_single_tab_meeting`.
    static let icon_single_tab_meeting = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_tab_meeting")
    /// SVG Image `icon_single_tab_meetingselect`.
    static let icon_single_tab_meetingselect = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_tab_meetingselect")
    /// SVG Image `icon_single_tab_orange`.
    static let icon_single_tab_orange = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_tab_orange")
    /// SVG Image `icon_single_tab_orange_select`.
    static let icon_single_tab_orange_select = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_tab_orange_select")
    /// SVG Image `icon_single_tab_contacts`.
    static let icon_single_tab_contacts = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_tab_contacts")
    /// SVG Image `icon_single_tab_contact_select`.
    static let icon_single_tab_contact_select = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_tab_contact_select")
    /// SVG Image `icon_single_tab_note`.
    static let icon_single_tab_note = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_tab_note")
    /// SVG Image `icon_single_tab_note_select`.
    static let icon_single_tab_note_select = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_tab_note_select")
    /// SVG Image `icon_single_tab_circle`.
    static let icon_single_tab_circle = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_tab_circle")
    /// SVG Image `icon_single_tab_circle_select`.
    static let icon_single_tab_circle_select = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_tab_circle_select")
    /// SVG Image `icon_single_tab_calendar`.
    static let icon_single_tab_calendar = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_tab_calendar")
    /// SVG Image `icon_single_tab_calendar_select`.
    static let icon_single_tab_calendar_select = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_tab_calendar_select")
    /// SVG Image `icon_single_tab_approve`.
    static let icon_single_tab_approve = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_tab_approve")
    /// SVG Image `icon_single_tab_approve_select`.
    static let icon_single_tab_approve_select = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_tab_approve_select")
    /// SVG Image `icon_single_tab_collect_select`.
    static let icon_single_tab_collect_select = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_tab_collect_select")
    /// SVG Image `icon_single_tab_knowledge_select`.
    static let icon_single_tab_knowledge_select = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_tab_knowledge_select")
    /// SVG Image `icon_single_tab_cloudspace`.
    static let icon_single_tab_cloudspace = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_tab_cloudspace")
    /// SVG Image `icon_single_contacts`.
    static let icon_single_contacts = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_contacts")
    /// SVG Image `icon_single_rank`.
    static let icon_single_rank = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_rank")
    /// SVG Image `icon_single_im_logged`.
    static let icon_single_im_logged = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_logged")
    /// SVG Image `icon_single_im_todopoint`.
    static let icon_single_im_todopoint = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_todopoint")
    /// SVG Image `icon_single_im_todo`.
    static let icon_single_im_todo = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_todo")
    /// SVG Image `icon_single_im_expression`.
    static let icon_single_im_expression = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_expression")
    /// SVG Image `icon_single_im_more`.
    static let icon_single_im_more = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_more")
    /// SVG Image `icon_single_delet`.
    static let icon_single_delet = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_delet")
    /// SVG Image `icon_single_im_multiplechoice`.
    static let icon_single_im_multiplechoice = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_multiplechoice")
    /// SVG Image `icon_single_im_translate`.
    static let icon_single_im_translate = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_translate")
    /// SVG Image `icon_single_im_groupmanage`.
    static let icon_single_im_groupmanage = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_groupmanage")
    /// SVG Image `icon_single_im_grouprank`.
    static let icon_single_im_grouprank = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_grouprank")
    /// SVG Image `icon_single_im_groupdelet`.
    static let icon_single_im_groupdelet = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_groupdelet")
    /// SVG Image `icon_single_im_groupview`.
    static let icon_single_im_groupview = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_groupview")
    /// SVG Image `icon_single_im_copy`.
    static let icon_single_im_copy = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_copy")
    /// SVG Image `icon_single_im_redpacket`.
    static let icon_single_im_redpacket = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_redpacket")
    /// SVG Image `icon_single_im_reply`.
    static let icon_single_im_reply = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_reply")
    /// SVG Image `icon_single_im_keyboard`.
    static let icon_single_im_keyboard = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_keyboard")
    /// SVG Image `icon_single_im_warning`.
    static let icon_single_im_warning = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_warning")
    /// SVG Image `icon_single_im_finished`.
    static let icon_single_im_finished = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_finished")
    /// SVG Image `icon_single_im_fail`.
    static let icon_single_im_fail = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_fail")
    /// SVG Image `icon_single_im_fresh`.
    static let icon_single_im_fresh = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_fresh")
    /// SVG Image `icon_single_im_shortcut`.
    static let icon_single_im_shortcut = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_shortcut")
    /// SVG Image `icon_single_im_card`.
    static let icon_single_im_card = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_card")
    /// SVG Image `icon_single_im_view`.
    static let icon_single_im_view = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_view")
    /// SVG Image `icon_single_im_photo`.
    static let icon_single_im_photo = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_photo")
    /// SVG Image `icon_single_im_rank`.
    static let icon_single_im_rank = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_rank")
    /// SVG Image `icon_single_im_noread`.
    static let icon_single_im_noread = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_noread")
    /// SVG Image `icon_single_im_recipt`.
    static let icon_single_im_recipt = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_recipt")
    /// SVG Image `icon_single_im_groupnotice`.
    static let icon_single_im_groupnotice = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_groupnotice")
    /// SVG Image `icon_single_im_group`.
    static let icon_single_im_group = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_group")
    /// SVG Image `icon_single_im_schedule_`.
    static let icon_single_im_schedule_ = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_schedule_")
    /// SVG Image `icon_single_im_time`.
    static let icon_single_im_time = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_time")
    /// SVG Image `icon_single_im_collect`.
    static let icon_single_im_collect = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_collect")
    /// SVG Image `icon_single_im_research`.
    static let icon_single_im_research = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_research")
    /// SVG Image `icon_single_im_remind`.
    static let icon_single_im_remind = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_remind")
    /// SVG Image `icon_single_im_add`.
    static let icon_single_im_add = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_add")
    /// SVG Image `icon_single_im_add_unselect`.
    static let icon_single_im_add_unselect = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_add_unselect")
    /// SVG Image `icon_single_im_add_select`.
    static let icon_single_im_add_select = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_add_select")
    /// SVG Image `icon_single_im_receiver`.
    static let icon_single_im_receiver = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_receiver")
    /// SVG Image `icon_single_im_call`.
    static let icon_single_im_call = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_call")
    /// SVG Image `icon_single_im_file`.
    static let icon_single_im_file = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_file")
    /// SVG Image `icon_single_im_photoalbum`.
    static let icon_single_im_photoalbum = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_photoalbum")
    /// SVG Image `icon_single_im_nomessage`.
    static let icon_single_im_nomessage = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_nomessage")
    /// SVG Image `icon_single_im_selected`.
    static let icon_single_im_selected = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_selected")
    /// SVG Image `icon_single_im_select`.
    static let icon_single_im_select = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_select")
    /// SVG Image `icon_single_im_loud`.
    static let icon_single_im_loud = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_loud")
    /// SVG Image `icon_single_im_user`.
    static let icon_single_im_user = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_user")
    /// SVG Image `icon_single_im_talk`.
    static let icon_single_im_talk = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_talk")
    /// SVG Image `icon_single_im_talkmessage`.
    static let icon_single_im_talkmessage = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_talkmessage")
    /// SVG Image `icon_single_im_cloudfile`.
    static let icon_single_im_cloudfile = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_cloudfile")
    /// SVG Image `icon_single_im_transpond`.
    static let icon_single_im_transpond = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_transpond")
    /// SVG Image `icon_single_calendar_edit`.
    static let icon_single_calendar_edit = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_calendar_edit")
    /// SVG Image `icon_single_calendar_busy`.
    static let icon_single_calendar_busy = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_calendar_busy")
    /// SVG Image `icon_single_calendar_user`.
    static let icon_single_calendar_user = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_calendar_user")
    /// SVG Image `icon_single_calendar_userright`.
    static let icon_single_calendar_userright = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_calendar_userright")
    /// SVG Image `icon_single_calendar_creator`.
    static let icon_single_calendar_creator = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_calendar_creator")
    /// SVG Image `icon_single_calendar_undetermind`.
    static let icon_single_calendar_undetermind = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_calendar_undetermind")
    /// SVG Image `icon_single_calendar_refuse`.
    static let icon_single_calendar_refuse = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_calendar_refuse")
    /// SVG Image `icon_single_calendar_undeterminded`.
    static let icon_single_calendar_undeterminded = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_calendar_undeterminded")
    /// SVG Image `icon_single_calendar_place`.
    static let icon_single_calendar_place = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_calendar_place")
    /// SVG Image `icon_single_calendar_share`.
    static let icon_single_calendar_share = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_calendar_share")
    /// SVG Image `icon_single_calendar_copy`.
    static let icon_single_calendar_copy = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_calendar_copy")
    /// SVG Image `icon_single_calendar_source`.
    static let icon_single_calendar_source = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_calendar_source")
    /// SVG Image `icon_single_calendar_meetinglist`.
    static let icon_single_calendar_meetinglist = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_calendar_meetinglist")
    /// SVG Image `icon_single_calendar_describe`.
    static let icon_single_calendar_describe = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_calendar_describe")
    /// SVG Image `icon_single_calendar_schedule`.
    static let icon_single_calendar_schedule = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_calendar_schedule")
    /// SVG Image `icon_single_calendar_updown`.
    static let icon_single_calendar_updown = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_calendar_updown")
    /// SVG Image `icon_single_calendar_threeday`.
    static let icon_single_calendar_threeday = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_calendar_threeday")
    /// SVG Image `icon_single_calendar_remind`.
    static let icon_single_calendar_remind = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_calendar_remind")
    /// SVG Image `icon_single_calendar_add`.
    static let icon_single_calendar_add = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_calendar_add")
    /// SVG Image `icon_single_calendar_file`.
    static let icon_single_calendar_file = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_calendar_file")
    /// SVG Image `icon_single_calendar_meeting`.
    static let icon_single_calendar_meeting = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_calendar_meeting")
    /// SVG Image `icon_single_calendar_invite`.
    static let icon_single_calendar_invite = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_calendar_invite")
    /// SVG Image `icon_single_calendar_userset`.
    static let icon_single_calendar_userset = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_calendar_userset")
    /// SVG Image `icon_single_calendar_repet`.
    static let icon_single_calendar_repet = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_calendar_repet")
    /// SVG Image `icon_single_calendar_create`.
    static let icon_single_calendar_create = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_calendar_create")
    /// SVG Image `icon_single_calendar_organizer`.
    static let icon_single_calendar_organizer = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_calendar_organizer")
    /// SVG Image `icon_single_edit`.
    static let icon_single_edit = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_edit")
    /// SVG Image `icon_single_tele`.
    static let icon_single_tele = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_tele")
    /// SVG Image `icon_single_share`.
    static let icon_single_share = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_share")
    /// SVG Image `icon_single_copymail`.
    static let icon_single_copymail = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_copymail")
    /// SVG Image `icon_single_state`.
    static let icon_single_state = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_state")
    /// SVG Image `icon_single_home`.
    static let icon_single_home = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_home")
    /// SVG Image `icon_single_squ_selcet`.
    static let icon_single_squ_selcet = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_squ_selcet")
    /// SVG Image `icon_single_play`.
    static let icon_single_play = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_play")
    /// SVG Image `icon_single_back`.
    static let icon_single_back = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_back")
    /// SVG Image `icon_single_close`.
    static let icon_single_close = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_close")
    /// SVG Image `icon_single_clean`.
    static let icon_single_clean = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_clean")
    /// SVG Image `icon_single_delet_circle`.
    static let icon_single_delet_circle = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_delet_circle")
    /// SVG Image `icon_single_selected`.
    static let icon_single_selected = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_selected")
    /// SVG Image `icon_single_tick`.
    static let icon_single_tick = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_tick")
    /// SVG Image `icon_single_down`.
    static let icon_single_down = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_down")
    /// SVG Image `icon_single_right`.
    static let icon_single_right = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_right")
    /// SVG Image `icon_single_warning`.
    static let icon_single_warning = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_warning")
    /// SVG Image `icon_single_calendar_select`.
    static let icon_single_calendar_select = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_calendar_select")
    /// SVG Image `icon_single_calendar_down`.
    static let icon_single_calendar_down = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_calendar_down")
    /// SVG Image `icon_single_calendar_unfold`.
    static let icon_single_calendar_unfold = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_calendar_unfold")
    /// SVG Image `icon_single_calendar_previewclose`.
    static let icon_single_calendar_previewclose = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_calendar_previewclose")
    /// SVG Image `icon_single_im_filtrate`.
    static let icon_single_im_filtrate = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_filtrate")
    /// SVG Image `icon_single_im_scan`.
    static let icon_single_im_scan = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_scan")
    /// SVG Image `icon_single_department`.
    static let icon_single_department = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_department")
    /// SVG Image `icon_single_group`.
    static let icon_single_group = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_group")
    /// SVG Image `icon_single_im_groups`.
    static let icon_single_im_groups = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_groups")
    /// SVG Image `icon_single_im_freshs`.
    static let icon_single_im_freshs = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_freshs")
    /// SVG Image `icon_single_homecircle`.
    static let icon_single_homecircle = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_homecircle")
    /// SVG Image `icon_single_money`.
    static let icon_single_money = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_money")
    /// SVG Image `icon_single_didi`.
    static let icon_single_didi = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_didi")
    /// SVG Image `icon_single_wechat`.
    static let icon_single_wechat = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_wechat")
    /// SVG Image `icon_single_payment`.
    static let icon_single_payment = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_payment")
    /// SVG Image `icon_single_ding`.
    static let icon_single_ding = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_ding")
    /// SVG Image `icon_single_groupmessage`.
    static let icon_single_groupmessage = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_groupmessage")
    /// SVG Image `icon_single_calendar_num`.
    static let icon_single_calendar_num = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_calendar_num")
    /// SVG Image `icon_single_calendar_more`.
    static let icon_single_calendar_more = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_calendar_more")
    /// SVG Image `icon_single_squ_selected`.
    static let icon_single_squ_selected = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_squ_selected")
    /// SVG Image `icon_single_calendar_timebusy`.
    static let icon_single_calendar_timebusy = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_calendar_timebusy")
    /// SVG Image `icon_multi_im_fresh`.
    static let icon_multi_im_fresh = Theme.image.Resource(bundle: Theme.bundle, name: "icon_multi_im_fresh")
    /// SVG Image `icon_multi_card`.
    static let icon_multi_card = Theme.image.Resource(bundle: Theme.bundle, name: "icon_multi_card")
    /// SVG Image `icon_multi_notice`.
    static let icon_multi_notice = Theme.image.Resource(bundle: Theme.bundle, name: "icon_multi_notice")
    /// SVG Image `icon_multi_research`.
    static let icon_multi_research = Theme.image.Resource(bundle: Theme.bundle, name: "icon_multi_research")
    /// SVG Image `icon_multi_pic`.
    static let icon_multi_pic = Theme.image.Resource(bundle: Theme.bundle, name: "icon_multi_pic")
    /// SVG Image `icon_multi_file`.
    static let icon_multi_file = Theme.image.Resource(bundle: Theme.bundle, name: "icon_multi_file")
    /// SVG Image `icon_multi_message`.
    static let icon_multi_message = Theme.image.Resource(bundle: Theme.bundle, name: "icon_multi_message")
    /// SVG Image `icon_multi_robot`.
    static let icon_multi_robot = Theme.image.Resource(bundle: Theme.bundle, name: "icon_multi_robot")
    /// SVG Image `icon_multi_attention`.
    static let icon_multi_attention = Theme.image.Resource(bundle: Theme.bundle, name: "icon_multi_attention")
    /// SVG Image `icon_multi_group`.
    static let icon_multi_group = Theme.image.Resource(bundle: Theme.bundle, name: "icon_multi_group")
    /// SVG Image `icon_multi_update`.
    static let icon_multi_update = Theme.image.Resource(bundle: Theme.bundle, name: "icon_multi_update")
    /// SVG Image `icon_multi_updating`.
    static let icon_multi_updating = Theme.image.Resource(bundle: Theme.bundle, name: "icon_multi_updating")
    /// SVG Image `icon_multi_service`.
    static let icon_multi_service = Theme.image.Resource(bundle: Theme.bundle, name: "icon_multi_service")
    /// SVG Image `icon_multi_set`.
    static let icon_multi_set = Theme.image.Resource(bundle: Theme.bundle, name: "icon_multi_set")
    /// SVG Image `icon_multi_collect`.
    static let icon_multi_collect = Theme.image.Resource(bundle: Theme.bundle, name: "icon_multi_collect")
    /// SVG Image `icon_multi_wallet`.
    static let icon_multi_wallet = Theme.image.Resource(bundle: Theme.bundle, name: "icon_multi_wallet")
    /// SVG Image `icon_multi_organise`.
    static let icon_multi_organise = Theme.image.Resource(bundle: Theme.bundle, name: "icon_multi_organise")
    /// SVG Image `icon_single_more`.
    static let icon_single_more = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_more")
    /// SVG Image `icon_single_todo_share`.
    static let icon_single_todo_share = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_todo_share")
    /// SVG Image `icon_single_todo_man`.
    static let icon_single_todo_man = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_todo_man")
    /// SVG Image `icon_single_todo_addhuman`.
    static let icon_single_todo_addhuman = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_todo_addhuman")
    /// SVG Image `icon_single_todo_addtime`.
    static let icon_single_todo_addtime = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_todo_addtime")
    /// SVG Image `icon_single_icontodo_addreminder`.
    static let icon_single_icontodo_addreminder = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_icontodo_addreminder")
    /// SVG Image `icon_single_todo_prior`.
    static let icon_single_todo_prior = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_todo_prior")
    /// SVG Image `icon_single_todo_deadline`.
    static let icon_single_todo_deadline = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_todo_deadline")
    /// SVG Image `icon_single_todo_createtime`.
    static let icon_single_todo_createtime = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_todo_createtime")
    /// SVG Image `icon_single_todo_updatetime`.
    static let icon_single_todo_updatetime = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_todo_updatetime")
    /// SVG Image `icon_single_todo_priorst`.
    static let icon_single_todo_priorst = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_todo_priorst")
    /// SVG Image `icon_single_todo_leader`.
    static let icon_single_todo_leader = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_todo_leader")
    /// SVG Image `icon_single_todo_adduser`.
    static let icon_single_todo_adduser = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_todo_adduser")
    /// SVG Image `icon_single_todo_menu`.
    static let icon_single_todo_menu = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_todo_menu")
    /// SVG Image `icon_single_todo_timeadd`.
    static let icon_single_todo_timeadd = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_todo_timeadd")
    /// SVG Image `icon_single_todo_remind`.
    static let icon_single_todo_remind = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_todo_remind")
    /// SVG Image `icon_single_todo_record`.
    static let icon_single_todo_record = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_todo_record")
    /// SVG Image `icon_single_im_todo2`.
    static let icon_single_im_todo2 = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_todo2")
    /// SVG Image `icon_single_todo_delete`.
    static let icon_single_todo_delete = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_todo_delete")
    /// SVG Image `icon_single_todo_success`.
    static let icon_single_todo_success = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_todo_success")
    /// SVG Image `icon_single_todo_retry`.
    static let icon_single_todo_retry = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_todo_retry")
    /// SVG Image `icon_single_todo_circle`.
    static let icon_single_todo_circle = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_todo_circle")
    /// SVG Image `icon_single_todo_moveon`.
    static let icon_single_todo_moveon = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_todo_moveon")
    /// SVG Image `icon_single_todo_paixu`.
    static let icon_single_todo_paixu = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_todo_paixu")
    /// SVG Image `icon_single_todo_rename`.
    static let icon_single_todo_rename = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_todo_rename")
    /// SVG Image `icon_single_todo_menudelete`.
    static let icon_single_todo_menudelete = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_todo_menudelete")
    /// SVG Image `icon_single_todo_setting`.
    static let icon_single_todo_setting = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_todo_setting")
    /// SVG Image `icon_single_todo_ondoing`.
    static let icon_single_todo_ondoing = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_todo_ondoing")
    /// SVG Image `icon_single_filter`.
    static let icon_single_filter = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_filter")
    /// SVG Image `icon_single_image`.
    static let icon_single_image = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_image")
    /// SVG Image `icon_single_link`.
    static let icon_single_link = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_link")
    /// SVG Image `icon_single_store_file`.
    static let icon_single_store_file = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_store_file")
    /// SVG Image `icon_single_id_card`.
    static let icon_single_id_card = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_id_card")
    /// SVG Image `icon_single_question`.
    static let icon_single_question = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_question")
    /// SVG Image `icon_single_card_home`.
    static let icon_single_card_home = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_card_home")
    /// SVG Image `icon_single_care`.
    static let icon_single_care = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_care")
    /// SVG Image `icon_single_lock`.
    static let icon_single_lock = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_lock")
    /// SVG Image `icon_single_exit_thread`.
    static let icon_single_exit_thread = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_exit_thread")
    /// SVG Image `icon_single_edit_thread`.
    static let icon_single_edit_thread = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_edit_thread")
    /// SVG Image `icon_single_pin02_thread`.
    static let icon_single_pin02_thread = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_pin02_thread")
    /// SVG Image `icon_single_pin01_thread`.
    static let icon_single_pin01_thread = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_pin01_thread")
    /// SVG Image `icon_single_thread_listpin`.
    static let icon_single_thread_listpin = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_thread_listpin")
    /// SVG Image `icon_single_thread_list`.
    static let icon_single_thread_list = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_thread_list")
    /// SVG Image `icon_single_search_topic`.
    static let icon_single_search_topic = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_search_topic")
    /// SVG Image `icon_single_shaixuan`.
    static let icon_single_shaixuan = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_shaixuan")
    /// SVG Image `icon_single_check_store`.
    static let icon_single_check_store = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_check_store")
    /// SVG Image `icon_single_cancel_store`.
    static let icon_single_cancel_store = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_cancel_store")
    /// SVG Image `icon_single_check_stored`.
    static let icon_single_check_stored = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_check_stored")
    /// SVG Image `icon_single_user_topic`.
    static let icon_single_user_topic = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_user_topic")
    /// SVG Image `icon_single_usergroup`.
    static let icon_single_usergroup = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_usergroup")
    /// SVG Image `icon_single_public_menu`.
    static let icon_single_public_menu = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_public_menu")
    /// SVG Image `icon_single_chat_group`.
    static let icon_single_chat_group = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_chat_group")
    /// SVG Image `icon_single_chat_public`.
    static let icon_single_chat_public = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_chat_public")
    /// SVG Image `icon_single_chat_outsider`.
    static let icon_single_chat_outsider = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_chat_outsider")
    /// SVG Image `icon_single_note`.
    static let icon_single_note = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_note")
    /// SVG Image `icon_single_fuceng_close`.
    static let icon_single_fuceng_close = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_fuceng_close")
    /// SVG Image `icon_single_thebest`.
    static let icon_single_thebest = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_thebest")
    /// SVG Image `icon_single_label`.
    static let icon_single_label = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_label")
    /// SVG Image `icon_single_message`.
    static let icon_single_message = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_message")
    /// SVG Image `icon_multi_todo_going`.
    static let icon_multi_todo_going = Theme.image.Resource(bundle: Theme.bundle, name: "icon_multi_todo_going")
    /// SVG Image `icon_multi_todo_lead`.
    static let icon_multi_todo_lead = Theme.image.Resource(bundle: Theme.bundle, name: "icon_multi_todo_lead")
    /// SVG Image `icon_multi_todo_accept`.
    static let icon_multi_todo_accept = Theme.image.Resource(bundle: Theme.bundle, name: "icon_multi_todo_accept")
    /// SVG Image `icon_multi_todo_finished`.
    static let icon_multi_todo_finished = Theme.image.Resource(bundle: Theme.bundle, name: "icon_multi_todo_finished")
    /// SVG Image `icon_multi_chat_usergroup`.
    static let icon_multi_chat_usergroup = Theme.image.Resource(bundle: Theme.bundle, name: "icon_multi_chat_usergroup")
    /// SVG Image `icon_multi_chat_public`.
    static let icon_multi_chat_public = Theme.image.Resource(bundle: Theme.bundle, name: "icon_multi_chat_public")
    /// SVG Image `icon_multi_chat_outside`.
    static let icon_multi_chat_outside = Theme.image.Resource(bundle: Theme.bundle, name: "icon_multi_chat_outside")
    /// SVG Image `icon_multi_chat_care`.
    static let icon_multi_chat_care = Theme.image.Resource(bundle: Theme.bundle, name: "icon_multi_chat_care")
    /// SVG Image `icon_multi_todo_chekbox`.
    static let icon_multi_todo_chekbox = Theme.image.Resource(bundle: Theme.bundle, name: "icon_multi_todo_chekbox")
    /// SVG Image `icon_single_calendar_up`.
    static let icon_single_calendar_up = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_calendar_up")
    /// SVG Image `icon_single_add`.
    static let icon_single_add = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_add")
    /// SVG Image `icon_single_calendar_accept`.
    static let icon_single_calendar_accept = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_calendar_accept")
    /// SVG Image `icon_single_calendar_accept_selected`.
    static let icon_single_calendar_accept_selected = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_calendar_accept_selected")
    /// SVG Image `icon_single_calendar_refuse_selected`.
    static let icon_single_calendar_refuse_selected = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_calendar_refuse_selected")
    /// SVG Image `icon_single_calendar_undetermind_selected`.
    static let icon_single_calendar_undetermind_selected = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_calendar_undetermind_selected")
    /// SVG Image `icon_single_im_retract`.
    static let icon_single_im_retract = Theme.image.Resource(bundle: Theme.bundle, name: "icon_single_im_retract")
}

// MARK: - Single Color Image 
@objc public extension Theme.image {
    
    /// `SVGImage(named: "icon_single_im_label", color: ..., size: ...)`
    static func icon_single_im_label(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_label, color, size)
    }

    /// `SVGImage(named: "icon_single_tab_knowledge", color: ..., size: ...)`
    static func icon_single_tab_knowledge(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_tab_knowledge, color, size)
    }

    /// `SVGImage(named: "icon_single_tab_cloud", color: ..., size: ...)`
    static func icon_single_tab_cloud(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_tab_cloud, color, size)
    }

    /// `SVGImage(named: "icon_single_store", color: ..., size: ...)`
    static func icon_single_store(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_store, color, size)
    }

    /// `SVGImage(named: "icon_single_tab_todo_select", color: ..., size: ...)`
    static func icon_single_tab_todo_select(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_tab_todo_select, color, size)
    }

    /// `SVGImage(named: "icon_single_tab_work", color: ..., size: ...)`
    static func icon_single_tab_work(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_tab_work, color, size)
    }

    /// `SVGImage(named: "icon_single_tab_collect", color: ..., size: ...)`
    static func icon_single_tab_collect(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_tab_collect, color, size)
    }

    /// `SVGImage(named: "icon_single_tab_dialogue", color: ..., size: ...)`
    static func icon_single_tab_dialogue(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_tab_dialogue, color, size)
    }

    /// `SVGImage(named: "icon_single_file", color: ..., size: ...)`
    static func icon_single_file(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_file, color, size)
    }

    /// `SVGImage(named: "icon_single_vpn", color: ..., size: ...)`
    static func icon_single_vpn(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_vpn, color, size)
    }

    /// `SVGImage(named: "icon_single_createmeeting", color: ..., size: ...)`
    static func icon_single_createmeeting(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_createmeeting, color, size)
    }

    /// `SVGImage(named: "icon_single_card", color: ..., size: ...)`
    static func icon_single_card(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_card, color, size)
    }

    /// `SVGImage(named: "icon_single_talking", color: ..., size: ...)`
    static func icon_single_talking(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_talking, color, size)
    }

    /// `SVGImage(named: "icon_single_pay", color: ..., size: ...)`
    static func icon_single_pay(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_pay, color, size)
    }

    /// `SVGImage(named: "icon_single_nomessage", color: ..., size: ...)`
    static func icon_single_nomessage(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_nomessage, color, size)
    }

    /// `SVGImage(named: "icon_single_scan", color: ..., size: ...)`
    static func icon_single_scan(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_scan, color, size)
    }

    /// `SVGImage(named: "icon_single_tab_todo", color: ..., size: ...)`
    static func icon_single_tab_todo(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_tab_todo, color, size)
    }

    /// `SVGImage(named: "icon_single_tab_dialogue_select", color: ..., size: ...)`
    static func icon_single_tab_dialogue_select(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_tab_dialogue_select, color, size)
    }

    /// `SVGImage(named: "icon_single_tab_more", color: ..., size: ...)`
    static func icon_single_tab_more(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_tab_more, color, size)
    }

    /// `SVGImage(named: "icon_single_tab_moreselect", color: ..., size: ...)`
    static func icon_single_tab_moreselect(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_tab_moreselect, color, size)
    }

    /// `SVGImage(named: "icon_single_tab_workselect", color: ..., size: ...)`
    static func icon_single_tab_workselect(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_tab_workselect, color, size)
    }

    /// `SVGImage(named: "icon_single_tab_meeting", color: ..., size: ...)`
    static func icon_single_tab_meeting(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_tab_meeting, color, size)
    }

    /// `SVGImage(named: "icon_single_tab_meetingselect", color: ..., size: ...)`
    static func icon_single_tab_meetingselect(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_tab_meetingselect, color, size)
    }

    /// `SVGImage(named: "icon_single_tab_orange", color: ..., size: ...)`
    static func icon_single_tab_orange(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_tab_orange, color, size)
    }

    /// `SVGImage(named: "icon_single_tab_orange_select", color: ..., size: ...)`
    static func icon_single_tab_orange_select(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_tab_orange_select, color, size)
    }

    /// `SVGImage(named: "icon_single_tab_contacts", color: ..., size: ...)`
    static func icon_single_tab_contacts(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_tab_contacts, color, size)
    }

    /// `SVGImage(named: "icon_single_tab_contact_select", color: ..., size: ...)`
    static func icon_single_tab_contact_select(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_tab_contact_select, color, size)
    }

    /// `SVGImage(named: "icon_single_tab_note", color: ..., size: ...)`
    static func icon_single_tab_note(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_tab_note, color, size)
    }

    /// `SVGImage(named: "icon_single_tab_note_select", color: ..., size: ...)`
    static func icon_single_tab_note_select(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_tab_note_select, color, size)
    }

    /// `SVGImage(named: "icon_single_tab_circle", color: ..., size: ...)`
    static func icon_single_tab_circle(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_tab_circle, color, size)
    }

    /// `SVGImage(named: "icon_single_tab_circle_select", color: ..., size: ...)`
    static func icon_single_tab_circle_select(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_tab_circle_select, color, size)
    }

    /// `SVGImage(named: "icon_single_tab_calendar", color: ..., size: ...)`
    static func icon_single_tab_calendar(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_tab_calendar, color, size)
    }

    /// `SVGImage(named: "icon_single_tab_calendar_select", color: ..., size: ...)`
    static func icon_single_tab_calendar_select(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_tab_calendar_select, color, size)
    }

    /// `SVGImage(named: "icon_single_tab_approve", color: ..., size: ...)`
    static func icon_single_tab_approve(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_tab_approve, color, size)
    }

    /// `SVGImage(named: "icon_single_tab_approve_select", color: ..., size: ...)`
    static func icon_single_tab_approve_select(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_tab_approve_select, color, size)
    }

    /// `SVGImage(named: "icon_single_tab_collect_select", color: ..., size: ...)`
    static func icon_single_tab_collect_select(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_tab_collect_select, color, size)
    }

    /// `SVGImage(named: "icon_single_tab_knowledge_select", color: ..., size: ...)`
    static func icon_single_tab_knowledge_select(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_tab_knowledge_select, color, size)
    }

    /// `SVGImage(named: "icon_single_tab_cloudspace", color: ..., size: ...)`
    static func icon_single_tab_cloudspace(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_tab_cloudspace, color, size)
    }

    /// `SVGImage(named: "icon_single_contacts", color: ..., size: ...)`
    static func icon_single_contacts(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_contacts, color, size)
    }

    /// `SVGImage(named: "icon_single_rank", color: ..., size: ...)`
    static func icon_single_rank(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_rank, color, size)
    }

    /// `SVGImage(named: "icon_single_im_logged", color: ..., size: ...)`
    static func icon_single_im_logged(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_logged, color, size)
    }

    /// `SVGImage(named: "icon_single_im_todopoint", color: ..., size: ...)`
    static func icon_single_im_todopoint(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_todopoint, color, size)
    }

    /// `SVGImage(named: "icon_single_im_todo", color: ..., size: ...)`
    static func icon_single_im_todo(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_todo, color, size)
    }

    /// `SVGImage(named: "icon_single_im_expression", color: ..., size: ...)`
    static func icon_single_im_expression(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_expression, color, size)
    }

    /// `SVGImage(named: "icon_single_im_more", color: ..., size: ...)`
    static func icon_single_im_more(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_more, color, size)
    }

    /// `SVGImage(named: "icon_single_delet", color: ..., size: ...)`
    static func icon_single_delet(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_delet, color, size)
    }

    /// `SVGImage(named: "icon_single_im_multiplechoice", color: ..., size: ...)`
    static func icon_single_im_multiplechoice(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_multiplechoice, color, size)
    }

    /// `SVGImage(named: "icon_single_im_translate", color: ..., size: ...)`
    static func icon_single_im_translate(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_translate, color, size)
    }

    /// `SVGImage(named: "icon_single_im_groupmanage", color: ..., size: ...)`
    static func icon_single_im_groupmanage(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_groupmanage, color, size)
    }

    /// `SVGImage(named: "icon_single_im_grouprank", color: ..., size: ...)`
    static func icon_single_im_grouprank(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_grouprank, color, size)
    }

    /// `SVGImage(named: "icon_single_im_groupdelet", color: ..., size: ...)`
    static func icon_single_im_groupdelet(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_groupdelet, color, size)
    }

    /// `SVGImage(named: "icon_single_im_groupview", color: ..., size: ...)`
    static func icon_single_im_groupview(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_groupview, color, size)
    }

    /// `SVGImage(named: "icon_single_im_copy", color: ..., size: ...)`
    static func icon_single_im_copy(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_copy, color, size)
    }

    /// `SVGImage(named: "icon_single_im_redpacket", color: ..., size: ...)`
    static func icon_single_im_redpacket(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_redpacket, color, size)
    }

    /// `SVGImage(named: "icon_single_im_reply", color: ..., size: ...)`
    static func icon_single_im_reply(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_reply, color, size)
    }

    /// `SVGImage(named: "icon_single_im_keyboard", color: ..., size: ...)`
    static func icon_single_im_keyboard(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_keyboard, color, size)
    }

    /// `SVGImage(named: "icon_single_im_warning", color: ..., size: ...)`
    static func icon_single_im_warning(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_warning, color, size)
    }

    /// `SVGImage(named: "icon_single_im_finished", color: ..., size: ...)`
    static func icon_single_im_finished(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_finished, color, size)
    }

    /// `SVGImage(named: "icon_single_im_fail", color: ..., size: ...)`
    static func icon_single_im_fail(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_fail, color, size)
    }

    /// `SVGImage(named: "icon_single_im_fresh", color: ..., size: ...)`
    static func icon_single_im_fresh(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_fresh, color, size)
    }

    /// `SVGImage(named: "icon_single_im_shortcut", color: ..., size: ...)`
    static func icon_single_im_shortcut(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_shortcut, color, size)
    }

    /// `SVGImage(named: "icon_single_im_card", color: ..., size: ...)`
    static func icon_single_im_card(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_card, color, size)
    }

    /// `SVGImage(named: "icon_single_im_view", color: ..., size: ...)`
    static func icon_single_im_view(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_view, color, size)
    }

    /// `SVGImage(named: "icon_single_im_photo", color: ..., size: ...)`
    static func icon_single_im_photo(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_photo, color, size)
    }

    /// `SVGImage(named: "icon_single_im_rank", color: ..., size: ...)`
    static func icon_single_im_rank(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_rank, color, size)
    }

    /// `SVGImage(named: "icon_single_im_noread", color: ..., size: ...)`
    static func icon_single_im_noread(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_noread, color, size)
    }

    /// `SVGImage(named: "icon_single_im_recipt", color: ..., size: ...)`
    static func icon_single_im_recipt(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_recipt, color, size)
    }

    /// `SVGImage(named: "icon_single_im_groupnotice", color: ..., size: ...)`
    static func icon_single_im_groupnotice(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_groupnotice, color, size)
    }

    /// `SVGImage(named: "icon_single_im_group", color: ..., size: ...)`
    static func icon_single_im_group(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_group, color, size)
    }

    /// `SVGImage(named: "icon_single_im_schedule_", color: ..., size: ...)`
    static func icon_single_im_schedule_(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_schedule_, color, size)
    }

    /// `SVGImage(named: "icon_single_im_time", color: ..., size: ...)`
    static func icon_single_im_time(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_time, color, size)
    }

    /// `SVGImage(named: "icon_single_im_collect", color: ..., size: ...)`
    static func icon_single_im_collect(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_collect, color, size)
    }

    /// `SVGImage(named: "icon_single_im_research", color: ..., size: ...)`
    static func icon_single_im_research(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_research, color, size)
    }

    /// `SVGImage(named: "icon_single_im_remind", color: ..., size: ...)`
    static func icon_single_im_remind(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_remind, color, size)
    }

    /// `SVGImage(named: "icon_single_im_add", color: ..., size: ...)`
    static func icon_single_im_add(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_add, color, size)
    }

    /// `SVGImage(named: "icon_single_im_add_unselect", color: ..., size: ...)`
    static func icon_single_im_add_unselect(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_add_unselect, color, size)
    }

    /// `SVGImage(named: "icon_single_im_add_select", color: ..., size: ...)`
    static func icon_single_im_add_select(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_add_select, color, size)
    }

    /// `SVGImage(named: "icon_single_im_receiver", color: ..., size: ...)`
    static func icon_single_im_receiver(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_receiver, color, size)
    }

    /// `SVGImage(named: "icon_single_im_call", color: ..., size: ...)`
    static func icon_single_im_call(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_call, color, size)
    }

    /// `SVGImage(named: "icon_single_im_file", color: ..., size: ...)`
    static func icon_single_im_file(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_file, color, size)
    }

    /// `SVGImage(named: "icon_single_im_photoalbum", color: ..., size: ...)`
    static func icon_single_im_photoalbum(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_photoalbum, color, size)
    }

    /// `SVGImage(named: "icon_single_im_nomessage", color: ..., size: ...)`
    static func icon_single_im_nomessage(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_nomessage, color, size)
    }

    /// `SVGImage(named: "icon_single_im_selected", color: ..., size: ...)`
    static func icon_single_im_selected(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_selected, color, size)
    }

    /// `SVGImage(named: "icon_single_im_select", color: ..., size: ...)`
    static func icon_single_im_select(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_select, color, size)
    }

    /// `SVGImage(named: "icon_single_im_loud", color: ..., size: ...)`
    static func icon_single_im_loud(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_loud, color, size)
    }

    /// `SVGImage(named: "icon_single_im_user", color: ..., size: ...)`
    static func icon_single_im_user(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_user, color, size)
    }

    /// `SVGImage(named: "icon_single_im_talk", color: ..., size: ...)`
    static func icon_single_im_talk(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_talk, color, size)
    }

    /// `SVGImage(named: "icon_single_im_talkmessage", color: ..., size: ...)`
    static func icon_single_im_talkmessage(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_talkmessage, color, size)
    }

    /// `SVGImage(named: "icon_single_im_cloudfile", color: ..., size: ...)`
    static func icon_single_im_cloudfile(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_cloudfile, color, size)
    }

    /// `SVGImage(named: "icon_single_im_transpond", color: ..., size: ...)`
    static func icon_single_im_transpond(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_transpond, color, size)
    }

    /// `SVGImage(named: "icon_single_calendar_edit", color: ..., size: ...)`
    static func icon_single_calendar_edit(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_calendar_edit, color, size)
    }

    /// `SVGImage(named: "icon_single_calendar_busy", color: ..., size: ...)`
    static func icon_single_calendar_busy(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_calendar_busy, color, size)
    }

    /// `SVGImage(named: "icon_single_calendar_user", color: ..., size: ...)`
    static func icon_single_calendar_user(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_calendar_user, color, size)
    }

    /// `SVGImage(named: "icon_single_calendar_userright", color: ..., size: ...)`
    static func icon_single_calendar_userright(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_calendar_userright, color, size)
    }

    /// `SVGImage(named: "icon_single_calendar_creator", color: ..., size: ...)`
    static func icon_single_calendar_creator(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_calendar_creator, color, size)
    }

    /// `SVGImage(named: "icon_single_calendar_undetermind", color: ..., size: ...)`
    static func icon_single_calendar_undetermind(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_calendar_undetermind, color, size)
    }

    /// `SVGImage(named: "icon_single_calendar_refuse", color: ..., size: ...)`
    static func icon_single_calendar_refuse(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_calendar_refuse, color, size)
    }

    /// `SVGImage(named: "icon_single_calendar_undeterminded", color: ..., size: ...)`
    static func icon_single_calendar_undeterminded(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_calendar_undeterminded, color, size)
    }

    /// `SVGImage(named: "icon_single_calendar_place", color: ..., size: ...)`
    static func icon_single_calendar_place(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_calendar_place, color, size)
    }

    /// `SVGImage(named: "icon_single_calendar_share", color: ..., size: ...)`
    static func icon_single_calendar_share(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_calendar_share, color, size)
    }

    /// `SVGImage(named: "icon_single_calendar_copy", color: ..., size: ...)`
    static func icon_single_calendar_copy(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_calendar_copy, color, size)
    }

    /// `SVGImage(named: "icon_single_calendar_source", color: ..., size: ...)`
    static func icon_single_calendar_source(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_calendar_source, color, size)
    }

    /// `SVGImage(named: "icon_single_calendar_meetinglist", color: ..., size: ...)`
    static func icon_single_calendar_meetinglist(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_calendar_meetinglist, color, size)
    }

    /// `SVGImage(named: "icon_single_calendar_describe", color: ..., size: ...)`
    static func icon_single_calendar_describe(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_calendar_describe, color, size)
    }

    /// `SVGImage(named: "icon_single_calendar_schedule", color: ..., size: ...)`
    static func icon_single_calendar_schedule(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_calendar_schedule, color, size)
    }

    /// `SVGImage(named: "icon_single_calendar_updown", color: ..., size: ...)`
    static func icon_single_calendar_updown(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_calendar_updown, color, size)
    }

    /// `SVGImage(named: "icon_single_calendar_threeday", color: ..., size: ...)`
    static func icon_single_calendar_threeday(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_calendar_threeday, color, size)
    }

    /// `SVGImage(named: "icon_single_calendar_remind", color: ..., size: ...)`
    static func icon_single_calendar_remind(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_calendar_remind, color, size)
    }

    /// `SVGImage(named: "icon_single_calendar_add", color: ..., size: ...)`
    static func icon_single_calendar_add(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_calendar_add, color, size)
    }

    /// `SVGImage(named: "icon_single_calendar_file", color: ..., size: ...)`
    static func icon_single_calendar_file(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_calendar_file, color, size)
    }

    /// `SVGImage(named: "icon_single_calendar_meeting", color: ..., size: ...)`
    static func icon_single_calendar_meeting(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_calendar_meeting, color, size)
    }

    /// `SVGImage(named: "icon_single_calendar_invite", color: ..., size: ...)`
    static func icon_single_calendar_invite(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_calendar_invite, color, size)
    }

    /// `SVGImage(named: "icon_single_calendar_userset", color: ..., size: ...)`
    static func icon_single_calendar_userset(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_calendar_userset, color, size)
    }

    /// `SVGImage(named: "icon_single_calendar_repet", color: ..., size: ...)`
    static func icon_single_calendar_repet(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_calendar_repet, color, size)
    }

    /// `SVGImage(named: "icon_single_calendar_create", color: ..., size: ...)`
    static func icon_single_calendar_create(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_calendar_create, color, size)
    }

    /// `SVGImage(named: "icon_single_calendar_organizer", color: ..., size: ...)`
    static func icon_single_calendar_organizer(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_calendar_organizer, color, size)
    }

    /// `SVGImage(named: "icon_single_edit", color: ..., size: ...)`
    static func icon_single_edit(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_edit, color, size)
    }

    /// `SVGImage(named: "icon_single_tele", color: ..., size: ...)`
    static func icon_single_tele(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_tele, color, size)
    }

    /// `SVGImage(named: "icon_single_share", color: ..., size: ...)`
    static func icon_single_share(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_share, color, size)
    }

    /// `SVGImage(named: "icon_single_copymail", color: ..., size: ...)`
    static func icon_single_copymail(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_copymail, color, size)
    }

    /// `SVGImage(named: "icon_single_state", color: ..., size: ...)`
    static func icon_single_state(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_state, color, size)
    }

    /// `SVGImage(named: "icon_single_home", color: ..., size: ...)`
    static func icon_single_home(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_home, color, size)
    }

    /// `SVGImage(named: "icon_single_squ_selcet", color: ..., size: ...)`
    static func icon_single_squ_selcet(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_squ_selcet, color, size)
    }

    /// `SVGImage(named: "icon_single_play", color: ..., size: ...)`
    static func icon_single_play(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_play, color, size)
    }

    /// `SVGImage(named: "icon_single_back", color: ..., size: ...)`
    static func icon_single_back(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_back, color, size)
    }

    /// `SVGImage(named: "icon_single_close", color: ..., size: ...)`
    static func icon_single_close(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_close, color, size)
    }

    /// `SVGImage(named: "icon_single_clean", color: ..., size: ...)`
    static func icon_single_clean(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_clean, color, size)
    }

    /// `SVGImage(named: "icon_single_delet_circle", color: ..., size: ...)`
    static func icon_single_delet_circle(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_delet_circle, color, size)
    }

    /// `SVGImage(named: "icon_single_selected", color: ..., size: ...)`
    static func icon_single_selected(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_selected, color, size)
    }

    /// `SVGImage(named: "icon_single_tick", color: ..., size: ...)`
    static func icon_single_tick(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_tick, color, size)
    }

    /// `SVGImage(named: "icon_single_down", color: ..., size: ...)`
    static func icon_single_down(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_down, color, size)
    }

    /// `SVGImage(named: "icon_single_right", color: ..., size: ...)`
    static func icon_single_right(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_right, color, size)
    }

    /// `SVGImage(named: "icon_single_warning", color: ..., size: ...)`
    static func icon_single_warning(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_warning, color, size)
    }

    /// `SVGImage(named: "icon_single_calendar_select", color: ..., size: ...)`
    static func icon_single_calendar_select(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_calendar_select, color, size)
    }

    /// `SVGImage(named: "icon_single_calendar_down", color: ..., size: ...)`
    static func icon_single_calendar_down(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_calendar_down, color, size)
    }

    /// `SVGImage(named: "icon_single_calendar_unfold", color: ..., size: ...)`
    static func icon_single_calendar_unfold(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_calendar_unfold, color, size)
    }

    /// `SVGImage(named: "icon_single_calendar_previewclose", color: ..., size: ...)`
    static func icon_single_calendar_previewclose(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_calendar_previewclose, color, size)
    }

    /// `SVGImage(named: "icon_single_im_filtrate", color: ..., size: ...)`
    static func icon_single_im_filtrate(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_filtrate, color, size)
    }

    /// `SVGImage(named: "icon_single_im_scan", color: ..., size: ...)`
    static func icon_single_im_scan(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_scan, color, size)
    }

    /// `SVGImage(named: "icon_single_department", color: ..., size: ...)`
    static func icon_single_department(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_department, color, size)
    }

    /// `SVGImage(named: "icon_single_group", color: ..., size: ...)`
    static func icon_single_group(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_group, color, size)
    }

    /// `SVGImage(named: "icon_single_im_groups", color: ..., size: ...)`
    static func icon_single_im_groups(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_groups, color, size)
    }

    /// `SVGImage(named: "icon_single_im_freshs", color: ..., size: ...)`
    static func icon_single_im_freshs(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_freshs, color, size)
    }

    /// `SVGImage(named: "icon_single_homecircle", color: ..., size: ...)`
    static func icon_single_homecircle(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_homecircle, color, size)
    }

    /// `SVGImage(named: "icon_single_money", color: ..., size: ...)`
    static func icon_single_money(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_money, color, size)
    }

    /// `SVGImage(named: "icon_single_didi", color: ..., size: ...)`
    static func icon_single_didi(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_didi, color, size)
    }

    /// `SVGImage(named: "icon_single_wechat", color: ..., size: ...)`
    static func icon_single_wechat(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_wechat, color, size)
    }

    /// `SVGImage(named: "icon_single_payment", color: ..., size: ...)`
    static func icon_single_payment(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_payment, color, size)
    }

    /// `SVGImage(named: "icon_single_ding", color: ..., size: ...)`
    static func icon_single_ding(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_ding, color, size)
    }

    /// `SVGImage(named: "icon_single_groupmessage", color: ..., size: ...)`
    static func icon_single_groupmessage(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_groupmessage, color, size)
    }

    /// `SVGImage(named: "icon_single_calendar_num", color: ..., size: ...)`
    static func icon_single_calendar_num(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_calendar_num, color, size)
    }

    /// `SVGImage(named: "icon_single_calendar_more", color: ..., size: ...)`
    static func icon_single_calendar_more(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_calendar_more, color, size)
    }

    /// `SVGImage(named: "icon_single_squ_selected", color: ..., size: ...)`
    static func icon_single_squ_selected(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_squ_selected, color, size)
    }

    /// `SVGImage(named: "icon_single_calendar_timebusy", color: ..., size: ...)`
    static func icon_single_calendar_timebusy(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_calendar_timebusy, color, size)
    }

    /// `SVGImage(named: "icon_single_more", color: ..., size: ...)`
    static func icon_single_more(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_more, color, size)
    }

    /// `SVGImage(named: "icon_single_todo_share", color: ..., size: ...)`
    static func icon_single_todo_share(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_todo_share, color, size)
    }

    /// `SVGImage(named: "icon_single_todo_man", color: ..., size: ...)`
    static func icon_single_todo_man(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_todo_man, color, size)
    }

    /// `SVGImage(named: "icon_single_todo_addhuman", color: ..., size: ...)`
    static func icon_single_todo_addhuman(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_todo_addhuman, color, size)
    }

    /// `SVGImage(named: "icon_single_todo_addtime", color: ..., size: ...)`
    static func icon_single_todo_addtime(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_todo_addtime, color, size)
    }

    /// `SVGImage(named: "icon_single_icontodo_addreminder", color: ..., size: ...)`
    static func icon_single_icontodo_addreminder(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_icontodo_addreminder, color, size)
    }

    /// `SVGImage(named: "icon_single_todo_prior", color: ..., size: ...)`
    static func icon_single_todo_prior(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_todo_prior, color, size)
    }

    /// `SVGImage(named: "icon_single_todo_deadline", color: ..., size: ...)`
    static func icon_single_todo_deadline(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_todo_deadline, color, size)
    }

    /// `SVGImage(named: "icon_single_todo_createtime", color: ..., size: ...)`
    static func icon_single_todo_createtime(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_todo_createtime, color, size)
    }

    /// `SVGImage(named: "icon_single_todo_updatetime", color: ..., size: ...)`
    static func icon_single_todo_updatetime(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_todo_updatetime, color, size)
    }

    /// `SVGImage(named: "icon_single_todo_priorst", color: ..., size: ...)`
    static func icon_single_todo_priorst(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_todo_priorst, color, size)
    }

    /// `SVGImage(named: "icon_single_todo_leader", color: ..., size: ...)`
    static func icon_single_todo_leader(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_todo_leader, color, size)
    }

    /// `SVGImage(named: "icon_single_todo_adduser", color: ..., size: ...)`
    static func icon_single_todo_adduser(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_todo_adduser, color, size)
    }

    /// `SVGImage(named: "icon_single_todo_menu", color: ..., size: ...)`
    static func icon_single_todo_menu(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_todo_menu, color, size)
    }

    /// `SVGImage(named: "icon_single_todo_timeadd", color: ..., size: ...)`
    static func icon_single_todo_timeadd(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_todo_timeadd, color, size)
    }

    /// `SVGImage(named: "icon_single_todo_remind", color: ..., size: ...)`
    static func icon_single_todo_remind(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_todo_remind, color, size)
    }

    /// `SVGImage(named: "icon_single_todo_record", color: ..., size: ...)`
    static func icon_single_todo_record(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_todo_record, color, size)
    }

    /// `SVGImage(named: "icon_single_im_todo2", color: ..., size: ...)`
    static func icon_single_im_todo2(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_todo2, color, size)
    }

    /// `SVGImage(named: "icon_single_todo_delete", color: ..., size: ...)`
    static func icon_single_todo_delete(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_todo_delete, color, size)
    }

    /// `SVGImage(named: "icon_single_todo_success", color: ..., size: ...)`
    static func icon_single_todo_success(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_todo_success, color, size)
    }

    /// `SVGImage(named: "icon_single_todo_retry", color: ..., size: ...)`
    static func icon_single_todo_retry(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_todo_retry, color, size)
    }

    /// `SVGImage(named: "icon_single_todo_circle", color: ..., size: ...)`
    static func icon_single_todo_circle(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_todo_circle, color, size)
    }

    /// `SVGImage(named: "icon_single_todo_moveon", color: ..., size: ...)`
    static func icon_single_todo_moveon(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_todo_moveon, color, size)
    }

    /// `SVGImage(named: "icon_single_todo_paixu", color: ..., size: ...)`
    static func icon_single_todo_paixu(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_todo_paixu, color, size)
    }

    /// `SVGImage(named: "icon_single_todo_rename", color: ..., size: ...)`
    static func icon_single_todo_rename(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_todo_rename, color, size)
    }

    /// `SVGImage(named: "icon_single_todo_menudelete", color: ..., size: ...)`
    static func icon_single_todo_menudelete(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_todo_menudelete, color, size)
    }

    /// `SVGImage(named: "icon_single_todo_setting", color: ..., size: ...)`
    static func icon_single_todo_setting(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_todo_setting, color, size)
    }

    /// `SVGImage(named: "icon_single_todo_ondoing", color: ..., size: ...)`
    static func icon_single_todo_ondoing(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_todo_ondoing, color, size)
    }

    /// `SVGImage(named: "icon_single_filter", color: ..., size: ...)`
    static func icon_single_filter(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_filter, color, size)
    }

    /// `SVGImage(named: "icon_single_image", color: ..., size: ...)`
    static func icon_single_image(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_image, color, size)
    }

    /// `SVGImage(named: "icon_single_link", color: ..., size: ...)`
    static func icon_single_link(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_link, color, size)
    }

    /// `SVGImage(named: "icon_single_store_file", color: ..., size: ...)`
    static func icon_single_store_file(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_store_file, color, size)
    }

    /// `SVGImage(named: "icon_single_id_card", color: ..., size: ...)`
    static func icon_single_id_card(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_id_card, color, size)
    }

    /// `SVGImage(named: "icon_single_question", color: ..., size: ...)`
    static func icon_single_question(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_question, color, size)
    }

    /// `SVGImage(named: "icon_single_card_home", color: ..., size: ...)`
    static func icon_single_card_home(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_card_home, color, size)
    }

    /// `SVGImage(named: "icon_single_care", color: ..., size: ...)`
    static func icon_single_care(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_care, color, size)
    }

    /// `SVGImage(named: "icon_single_lock", color: ..., size: ...)`
    static func icon_single_lock(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_lock, color, size)
    }

    /// `SVGImage(named: "icon_single_exit_thread", color: ..., size: ...)`
    static func icon_single_exit_thread(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_exit_thread, color, size)
    }

    /// `SVGImage(named: "icon_single_edit_thread", color: ..., size: ...)`
    static func icon_single_edit_thread(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_edit_thread, color, size)
    }

    /// `SVGImage(named: "icon_single_pin02_thread", color: ..., size: ...)`
    static func icon_single_pin02_thread(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_pin02_thread, color, size)
    }

    /// `SVGImage(named: "icon_single_pin01_thread", color: ..., size: ...)`
    static func icon_single_pin01_thread(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_pin01_thread, color, size)
    }

    /// `SVGImage(named: "icon_single_thread_listpin", color: ..., size: ...)`
    static func icon_single_thread_listpin(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_thread_listpin, color, size)
    }

    /// `SVGImage(named: "icon_single_thread_list", color: ..., size: ...)`
    static func icon_single_thread_list(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_thread_list, color, size)
    }

    /// `SVGImage(named: "icon_single_search_topic", color: ..., size: ...)`
    static func icon_single_search_topic(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_search_topic, color, size)
    }

    /// `SVGImage(named: "icon_single_shaixuan", color: ..., size: ...)`
    static func icon_single_shaixuan(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_shaixuan, color, size)
    }

    /// `SVGImage(named: "icon_single_check_store", color: ..., size: ...)`
    static func icon_single_check_store(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_check_store, color, size)
    }

    /// `SVGImage(named: "icon_single_cancel_store", color: ..., size: ...)`
    static func icon_single_cancel_store(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_cancel_store, color, size)
    }

    /// `SVGImage(named: "icon_single_check_stored", color: ..., size: ...)`
    static func icon_single_check_stored(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_check_stored, color, size)
    }

    /// `SVGImage(named: "icon_single_user_topic", color: ..., size: ...)`
    static func icon_single_user_topic(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_user_topic, color, size)
    }

    /// `SVGImage(named: "icon_single_usergroup", color: ..., size: ...)`
    static func icon_single_usergroup(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_usergroup, color, size)
    }

    /// `SVGImage(named: "icon_single_public_menu", color: ..., size: ...)`
    static func icon_single_public_menu(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_public_menu, color, size)
    }

    /// `SVGImage(named: "icon_single_chat_group", color: ..., size: ...)`
    static func icon_single_chat_group(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_chat_group, color, size)
    }

    /// `SVGImage(named: "icon_single_chat_public", color: ..., size: ...)`
    static func icon_single_chat_public(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_chat_public, color, size)
    }

    /// `SVGImage(named: "icon_single_chat_outsider", color: ..., size: ...)`
    static func icon_single_chat_outsider(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_chat_outsider, color, size)
    }

    /// `SVGImage(named: "icon_single_note", color: ..., size: ...)`
    static func icon_single_note(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_note, color, size)
    }

    /// `SVGImage(named: "icon_single_fuceng_close", color: ..., size: ...)`
    static func icon_single_fuceng_close(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_fuceng_close, color, size)
    }

    /// `SVGImage(named: "icon_single_thebest", color: ..., size: ...)`
    static func icon_single_thebest(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_thebest, color, size)
    }

    /// `SVGImage(named: "icon_single_label", color: ..., size: ...)`
    static func icon_single_label(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_label, color, size)
    }

    /// `SVGImage(named: "icon_single_message", color: ..., size: ...)`
    static func icon_single_message(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_message, color, size)
    }

    /// `SVGImage(named: "icon_single_calendar_up", color: ..., size: ...)`
    static func icon_single_calendar_up(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_calendar_up, color, size)
    }

    /// `SVGImage(named: "icon_single_add", color: ..., size: ...)`
    static func icon_single_add(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_add, color, size)
    }

    /// `SVGImage(named: "icon_single_calendar_accept", color: ..., size: ...)`
    static func icon_single_calendar_accept(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_calendar_accept, color, size)
    }

    /// `SVGImage(named: "icon_single_calendar_accept_selected", color: ..., size: ...)`
    static func icon_single_calendar_accept_selected(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_calendar_accept_selected, color, size)
    }

    /// `SVGImage(named: "icon_single_calendar_refuse_selected", color: ..., size: ...)`
    static func icon_single_calendar_refuse_selected(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_calendar_refuse_selected, color, size)
    }

    /// `SVGImage(named: "icon_single_calendar_undetermind_selected", color: ..., size: ...)`
    static func icon_single_calendar_undetermind_selected(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_calendar_undetermind_selected, color, size)
    }

    /// `SVGImage(named: "icon_single_im_retract", color: ..., size: ...)`
    static func icon_single_im_retract(color: UIColor? = nil, size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_single_im_retract, color, size)
    }
}

// MARK: - Multi Color Image 
@objc public extension Theme.image {
    
    /// `SVGImage(named: "icon_multi_im_fresh", size: ...)`
    static func icon_multi_im_fresh(size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_multi_im_fresh, size)
    }

    /// `SVGImage(named: "icon_multi_card", size: ...)`
    static func icon_multi_card(size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_multi_card, size)
    }

    /// `SVGImage(named: "icon_multi_notice", size: ...)`
    static func icon_multi_notice(size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_multi_notice, size)
    }

    /// `SVGImage(named: "icon_multi_research", size: ...)`
    static func icon_multi_research(size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_multi_research, size)
    }

    /// `SVGImage(named: "icon_multi_pic", size: ...)`
    static func icon_multi_pic(size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_multi_pic, size)
    }

    /// `SVGImage(named: "icon_multi_file", size: ...)`
    static func icon_multi_file(size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_multi_file, size)
    }

    /// `SVGImage(named: "icon_multi_message", size: ...)`
    static func icon_multi_message(size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_multi_message, size)
    }

    /// `SVGImage(named: "icon_multi_robot", size: ...)`
    static func icon_multi_robot(size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_multi_robot, size)
    }

    /// `SVGImage(named: "icon_multi_attention", size: ...)`
    static func icon_multi_attention(size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_multi_attention, size)
    }

    /// `SVGImage(named: "icon_multi_group", size: ...)`
    static func icon_multi_group(size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_multi_group, size)
    }

    /// `SVGImage(named: "icon_multi_update", size: ...)`
    static func icon_multi_update(size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_multi_update, size)
    }

    /// `SVGImage(named: "icon_multi_updating", size: ...)`
    static func icon_multi_updating(size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_multi_updating, size)
    }

    /// `SVGImage(named: "icon_multi_service", size: ...)`
    static func icon_multi_service(size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_multi_service, size)
    }

    /// `SVGImage(named: "icon_multi_set", size: ...)`
    static func icon_multi_set(size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_multi_set, size)
    }

    /// `SVGImage(named: "icon_multi_collect", size: ...)`
    static func icon_multi_collect(size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_multi_collect, size)
    }

    /// `SVGImage(named: "icon_multi_wallet", size: ...)`
    static func icon_multi_wallet(size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_multi_wallet, size)
    }

    /// `SVGImage(named: "icon_multi_organise", size: ...)`
    static func icon_multi_organise(size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_multi_organise, size)
    }

    /// `SVGImage(named: "icon_multi_todo_going", size: ...)`
    static func icon_multi_todo_going(size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_multi_todo_going, size)
    }

    /// `SVGImage(named: "icon_multi_todo_lead", size: ...)`
    static func icon_multi_todo_lead(size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_multi_todo_lead, size)
    }

    /// `SVGImage(named: "icon_multi_todo_accept", size: ...)`
    static func icon_multi_todo_accept(size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_multi_todo_accept, size)
    }

    /// `SVGImage(named: "icon_multi_todo_finished", size: ...)`
    static func icon_multi_todo_finished(size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_multi_todo_finished, size)
    }

    /// `SVGImage(named: "icon_multi_chat_usergroup", size: ...)`
    static func icon_multi_chat_usergroup(size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_multi_chat_usergroup, size)
    }

    /// `SVGImage(named: "icon_multi_chat_public", size: ...)`
    static func icon_multi_chat_public(size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_multi_chat_public, size)
    }

    /// `SVGImage(named: "icon_multi_chat_outside", size: ...)`
    static func icon_multi_chat_outside(size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_multi_chat_outside, size)
    }

    /// `SVGImage(named: "icon_multi_chat_care", size: ...)`
    static func icon_multi_chat_care(size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_multi_chat_care, size)
    }

    /// `SVGImage(named: "icon_multi_todo_chekbox", size: ...)`
    static func icon_multi_todo_chekbox(size: CGSize = .zero) -> UIImage? {
        getDynamicImage(.icon_multi_todo_chekbox, size)
    }
}
