//
// This is a generated file, do not edit!
// Generated by UIResource service, see http://dc-design.intra.xiaojukeji.com/
//

import UIKit

/**
 * @brief 动态颜色API
 *
 * $Key: 颜色在资源库中Key值，也是业务调用唯一标识符；
 * $LightColor: 颜色在浅色模式下对应色值；
 * $DarkColor: 颜色在深色模式下对应色值；
 * $DefaultColor: 当资源库主题切换异常时，颜色的默认色值，目前与$LightColor保持一致；
 *
 * For example:
 *  static var $Key: UIColor { getDynamicColor("$Key", ["$LightColor", "$DarkColor"], UIColor(rgba: "$DefaultColor")) }
 *  static var $Key: CGColor { getDynamicColor("$Key", ["$LightColor", "$DarkColor"], UIColor(rgba: "$DefaultColor").cgColor) }
 */

// MARK: - UIColor
@objc public extension UIColor {
    
    /// Light => #333333ff, Dark => #ffffffe6
    static var common_level1_color: UIColor {
        getDynamicColor("common_level1_color", ["#333333ff", "#ffffffe6"], UIColor(rgba: "#333333ff"))
    }

    /// Light => #666666ff, Dark => #ffffff99
    static var common_level2_color: UIColor {
        getDynamicColor("common_level2_color", ["#666666ff", "#ffffff99"], UIColor(rgba: "#666666ff"))
    }

    /// Light => #999999ff, Dark => #ffffff80
    static var common_level3_color: UIColor {
        getDynamicColor("common_level3_color", ["#999999ff", "#ffffff80"], UIColor(rgba: "#999999ff"))
    }

    /// Light => #abababff, Dark => #ffffff66
    static var common_level4_color: UIColor {
        getDynamicColor("common_level4_color", ["#abababff", "#ffffff66"], UIColor(rgba: "#abababff"))
    }

    /// Light => #bbbbbbff, Dark => #ffffff40
    static var common_level5_color: UIColor {
        getDynamicColor("common_level5_color", ["#bbbbbbff", "#ffffff40"], UIColor(rgba: "#bbbbbbff"))
    }

    /// Light => #ffffffff, Dark => #ffffffeb
    static var common_level6_color: UIColor {
        getDynamicColor("common_level6_color", ["#ffffffff", "#ffffffeb"], UIColor(rgba: "#ffffffff"))
    }

    /// Light => #e2e2e233, Dark => #e2e2e20a
    static var common_level_watermark_color: UIColor {
        getDynamicColor("common_level_watermark_color", ["#e2e2e233", "#e2e2e20a"], UIColor(rgba: "#e2e2e233"))
    }

    /// Light => #e8e8e8ff, Dark => #ffffff1f
    static var common_line1_color: UIColor {
        getDynamicColor("common_line1_color", ["#e8e8e8ff", "#ffffff1f"], UIColor(rgba: "#e8e8e8ff"))
    }

    /// Light => #eeeeeeff, Dark => #ffffff14
    static var common_line2_color: UIColor {
        getDynamicColor("common_line2_color", ["#eeeeeeff", "#ffffff14"], UIColor(rgba: "#eeeeeeff"))
    }

    /// Light => #999999ff, Dark => #ffffff66
    static var common_line3_color: UIColor {
        getDynamicColor("common_line3_color", ["#999999ff", "#ffffff66"], UIColor(rgba: "#999999ff"))
    }

    /// Light => #ffffffff, Dark => #1a1a1afc
    static var common_line4_color: UIColor {
        getDynamicColor("common_line4_color", ["#ffffffff", "#1a1a1afc"], UIColor(rgba: "#ffffffff"))
    }

    /// Light => #f7f7f7ff, Dark => #0e0e0eff
    static var common_bg1_color: UIColor {
        getDynamicColor("common_bg1_color", ["#f7f7f7ff", "#0e0e0eff"], UIColor(rgba: "#f7f7f7ff"))
    }

    /// Light => #ffffffff, Dark => #1a1a1aff
    static var common_bg2_color: UIColor {
        getDynamicColor("common_bg2_color", ["#ffffffff", "#1a1a1aff"], UIColor(rgba: "#ffffffff"))
    }

    /// Light => #f7f7f7ff, Dark => #262626fc
    static var common_bg3_color: UIColor {
        getDynamicColor("common_bg3_color", ["#f7f7f7ff", "#262626fc"], UIColor(rgba: "#f7f7f7ff"))
    }

    /// Light => #f3f3f3ff, Dark => #2a2a2aff
    static var common_bg4_color: UIColor {
        getDynamicColor("common_bg4_color", ["#f3f3f3ff", "#2a2a2aff"], UIColor(rgba: "#f3f3f3ff"))
    }

    /// Light => #e8e8e8ff, Dark => #ffffff40
    static var common_bg5_color: UIColor {
        getDynamicColor("common_bg5_color", ["#e8e8e8ff", "#ffffff40"], UIColor(rgba: "#e8e8e8ff"))
    }

    /// Light => #ffffffff, Dark => #262626ff
    static var common_bg6_color: UIColor {
        getDynamicColor("common_bg6_color", ["#ffffffff", "#262626ff"], UIColor(rgba: "#ffffffff"))
    }

    /// Light => #ffffffff, Dark => #3e3e3eff
    static var common_bg7_color: UIColor {
        getDynamicColor("common_bg7_color", ["#ffffffff", "#3e3e3eff"], UIColor(rgba: "#ffffffff"))
    }

    /// Light => #333333ff, Dark => #d15731fc
    static var common_bg8_color: UIColor {
        getDynamicColor("common_bg8_color", ["#333333ff", "#d15731fc"], UIColor(rgba: "#333333ff"))
    }

    /// Light => #343434ff, Dark => #3e3e3eff
    static var common_bg9_color: UIColor {
        getDynamicColor("common_bg9_color", ["#343434ff", "#3e3e3eff"], UIColor(rgba: "#343434ff"))
    }

    /// Light => #f7f7f7ff, Dark => #1a1a1aff
    static var common_bg11_color: UIColor {
        getDynamicColor("common_bg11_color", ["#f7f7f7ff", "#1a1a1aff"], UIColor(rgba: "#f7f7f7ff"))
    }

    /// Light => #0000001a, Dark => #ffffff1a
    static var common_bg10_color: UIColor {
        getDynamicColor("common_bg10_color", ["#0000001a", "#ffffff1a"], UIColor(rgba: "#0000001a"))
    }

    /// Light => #f2f2f2ff, Dark => #ffffff14
    static var common_bg_touch1_color: UIColor {
        getDynamicColor("common_bg_touch1_color", ["#f2f2f2ff", "#ffffff14"], UIColor(rgba: "#f2f2f2ff"))
    }

    /// Light => #ffffff33, Dark => #00000033
    static var common_bg_touch2_color: UIColor {
        getDynamicColor("common_bg_touch2_color", ["#ffffff33", "#00000033"], UIColor(rgba: "#ffffff33"))
    }

    /// Light => #00000066, Dark => #00000099
    static var common_bg_mask_color: UIColor {
        getDynamicColor("common_bg_mask_color", ["#00000066", "#00000099"], UIColor(rgba: "#00000066"))
    }

    /// Light => #ffffff80, Dark => #1a1a1a80
    static var common_bg_mask2_color: UIColor {
        getDynamicColor("common_bg_mask2_color", ["#ffffff80", "#1a1a1a80"], UIColor(rgba: "#ffffff80"))
    }

    /// Light => #0000001f, Dark => #0000001f
    static var common_shadow1_color: UIColor {
        getDynamicColor("common_shadow1_color", ["#0000001f", "#0000001f"], UIColor(rgba: "#0000001f"))
    }

    /// Light => #fd7443ff, Dark => #d15731ff
    static var common_orange1_color: UIColor {
        getDynamicColor("common_orange1_color", ["#fd7443ff", "#d15731ff"], UIColor(rgba: "#fd7443ff"))
    }

    /// Light => #fd744366, Dark => #d1573166
    static var common_orange2_color: UIColor {
        getDynamicColor("common_orange2_color", ["#fd744366", "#d1573166"], UIColor(rgba: "#fd744366"))
    }

    /// Light => #fd74431f, Dark => #d1573124
    static var common_orange3_color: UIColor {
        getDynamicColor("common_orange3_color", ["#fd74431f", "#d1573124"], UIColor(rgba: "#fd74431f"))
    }

    /// Light => #ff9347ff, Dark => #c0632bff
    static var common_orange4_color: UIColor {
        getDynamicColor("common_orange4_color", ["#ff9347ff", "#c0632bff"], UIColor(rgba: "#ff9347ff"))
    }

    /// Light => #f14237ff, Dark => #bd3936ff
    static var common_red1_color: UIColor {
        getDynamicColor("common_red1_color", ["#f14237ff", "#bd3936ff"], UIColor(rgba: "#f14237ff"))
    }

    /// Light => #feecedff, Dark => #ff505a1f
    static var common_red2_color: UIColor {
        getDynamicColor("common_red2_color", ["#feecedff", "#ff505a1f"], UIColor(rgba: "#feecedff"))
    }

    /// Light => #7f8691ff, Dark => #8f99a8ff
    static var common_Bluishgrey1_color: UIColor {
        getDynamicColor("common_Bluishgrey1_color", ["#7f8691ff", "#8f99a8ff"], UIColor(rgba: "#7f8691ff"))
    }

    /// Light => #e8eef8ff, Dark => #e8eef824
    static var common_Bluishgrey2_color: UIColor {
        getDynamicColor("common_Bluishgrey2_color", ["#e8eef8ff", "#e8eef824"], UIColor(rgba: "#e8eef8ff"))
    }

    /// Light => #dee3e8ff, Dark => #1a2432ff
    static var common_Bluishgrey3_color: UIColor {
        getDynamicColor("common_Bluishgrey3_color", ["#dee3e8ff", "#1a2432ff"], UIColor(rgba: "#dee3e8ff"))
    }

    /// Light => #dfe1e6ff, Dark => #1d293aff
    static var common_Bluishgrey4_color: UIColor {
        getDynamicColor("common_Bluishgrey4_color", ["#dfe1e6ff", "#1d293aff"], UIColor(rgba: "#dfe1e6ff"))
    }

    /// Light => #b9bec5ff, Dark => #73757aff
    static var common_Bluishgrey5_color: UIColor {
        getDynamicColor("common_Bluishgrey5_color", ["#b9bec5ff", "#73757aff"], UIColor(rgba: "#b9bec5ff"))
    }

    /// Light => #3160a4ff, Dark => #527fb6ff
    static var common_blue1_color: UIColor {
        getDynamicColor("common_blue1_color", ["#3160a4ff", "#527fb6ff"], UIColor(rgba: "#3160a4ff"))
    }

    /// Light => #5494ffff, Dark => #70a0feff
    static var common_blue2_color: UIColor {
        getDynamicColor("common_blue2_color", ["#5494ffff", "#70a0feff"], UIColor(rgba: "#5494ffff"))
    }

    /// Light => #e6efffff, Dark => #5494ff33
    static var common_blue3_color: UIColor {
        getDynamicColor("common_blue3_color", ["#e6efffff", "#5494ff33"], UIColor(rgba: "#e6efffff"))
    }

    /// Light => #5e7dffff, Dark => #84a1ffff
    static var common_blue4_color: UIColor {
        getDynamicColor("common_blue4_color", ["#5e7dffff", "#84a1ffff"], UIColor(rgba: "#5e7dffff"))
    }

    /// Light => #6ca3ffff, Dark => #3f6cc9ff
    static var common_blue5_color: UIColor {
        getDynamicColor("common_blue5_color", ["#6ca3ffff", "#3f6cc9ff"], UIColor(rgba: "#6ca3ffff"))
    }

    /// Light => #2cbfa4ff, Dark => #58ccb3ff
    static var common_turquoise1_color: UIColor {
        getDynamicColor("common_turquoise1_color", ["#2cbfa4ff", "#58ccb3ff"], UIColor(rgba: "#2cbfa4ff"))
    }

    /// Light => #00d5b3ff, Dark => #0c9183ff
    static var common_turquoise2_color: UIColor {
        getDynamicColor("common_turquoise2_color", ["#00d5b3ff", "#0c9183ff"], UIColor(rgba: "#00d5b3ff"))
    }

    /// Light => #fffbeaff, Dark => #2d2819ff
    static var common_yellow1_color: UIColor {
        getDynamicColor("common_yellow1_color", ["#fffbeaff", "#2d2819ff"], UIColor(rgba: "#fffbeaff"))
    }

    /// Light => #61c4f2ff, Dark => #2476a7ff
    static var common_wathet1_color: UIColor {
        getDynamicColor("common_wathet1_color", ["#61c4f2ff", "#2476a7ff"], UIColor(rgba: "#61c4f2ff"))
    }

    /// Light => #66c862ff, Dark => #28822aff
    static var common_green1_color: UIColor {
        getDynamicColor("common_green1_color", ["#66c862ff", "#28822aff"], UIColor(rgba: "#66c862ff"))
    }

    /// Light => #f8bb06ff, Dark => #ae7c0bff
    static var common_yellow2_color: UIColor {
        getDynamicColor("common_yellow2_color", ["#f8bb06ff", "#ae7c0bff"], UIColor(rgba: "#f8bb06ff"))
    }

    /// Light => #f46dbeff, Dark => #b7398bff
    static var common_carmine1_color: UIColor {
        getDynamicColor("common_carmine1_color", ["#f46dbeff", "#b7398bff"], UIColor(rgba: "#f46dbeff"))
    }

    /// Light => #db7de9ff, Dark => #9538aaff
    static var common_violet1_color: UIColor {
        getDynamicColor("common_violet1_color", ["#db7de9ff", "#9538aaff"], UIColor(rgba: "#db7de9ff"))
    }

    /// Light => #af82f9ff, Dark => #7248c5ff
    static var common_purple1_color: UIColor {
        getDynamicColor("common_purple1_color", ["#af82f9ff", "#7248c5ff"], UIColor(rgba: "#af82f9ff"))
    }

    /// Light => #8391efff, Dark => #4651b9ff
    static var common_indigo1_color: UIColor {
        getDynamicColor("common_indigo1_color", ["#8391efff", "#4651b9ff"], UIColor(rgba: "#8391efff"))
    }

    /// Light => #f18b001a, Dark => #f18b001f
    static var common_yellow3_color: UIColor {
        getDynamicColor("common_yellow3_color", ["#f18b001a", "#f18b001f"], UIColor(rgba: "#f18b001a"))
    }

    /// Light => #f18b00ff, Dark => #d27900ff
    static var common_yellow4_color: UIColor {
        getDynamicColor("common_yellow4_color", ["#f18b00ff", "#d27900ff"], UIColor(rgba: "#f18b00ff"))
    }

    /// Light => #ffffffff, Dark => #0e0e0efc
    static var common_bg12_color: UIColor {
        getDynamicColor("common_bg12_color", ["#ffffffff", "#0e0e0efc"], UIColor(rgba: "#ffffffff"))
    }

    /// Light => #ffffff4d, Dark => #ffffff4d
    static var common_bg13_color: UIColor {
        getDynamicColor("common_bg13_color", ["#ffffff4d", "#ffffff4d"], UIColor(rgba: "#ffffff4d"))
    }

    /// Light => #fd744314, Dark => #d1573114
    static var common_bg15_color: UIColor {
        getDynamicColor("common_bg15_color", ["#fd744314", "#d1573114"], UIColor(rgba: "#fd744314"))
    }

    /// Light => #e6e6e7ff, Dark => #535353ff
    static var common_bg18_color: UIColor {
        getDynamicColor("common_bg18_color", ["#e6e6e7ff", "#535353ff"], UIColor(rgba: "#e6e6e7ff"))
    }

    /// Light => #cdcdcdff, Dark => #393939ff
    static var common_bg19_color: UIColor {
        getDynamicColor("common_bg19_color", ["#cdcdcdff", "#393939ff"], UIColor(rgba: "#cdcdcdff"))
    }

    /// Light => #c54e00ff, Dark => #c54e00ff
    static var common_orange5_color: UIColor {
        getDynamicColor("common_orange5_color", ["#c54e00ff", "#c54e00ff"], UIColor(rgba: "#c54e00ff"))
    }

    /// Light => #ff8628ff, Dark => #cc6725ff
    static var common_orange6_color: UIColor {
        getDynamicColor("common_orange6_color", ["#ff8628ff", "#cc6725ff"], UIColor(rgba: "#ff8628ff"))
    }

    /// Light => #fff4e9ff, Dark => #4f2a0cff
    static var common_orange7_color: UIColor {
        getDynamicColor("common_orange7_color", ["#fff4e9ff", "#4f2a0cff"], UIColor(rgba: "#fff4e9ff"))
    }

    /// Light => #c54e00ff, Dark => #e7a87aff
    static var common_orange8_color: UIColor {
        getDynamicColor("common_orange8_color", ["#c54e00ff", "#e7a87aff"], UIColor(rgba: "#c54e00ff"))
    }

    /// Light => #ff6f50ff, Dark => #c73514ff
    static var common_red_checkbox_color: UIColor {
        getDynamicColor("common_red_checkbox_color", ["#ff6f50ff", "#c73514ff"], UIColor(rgba: "#ff6f50ff"))
    }

    /// Light => #ffa500ff, Dark => #d58a00ff
    static var common_yellow_checkbox_color: UIColor {
        getDynamicColor("common_yellow_checkbox_color", ["#ffa500ff", "#d58a00ff"], UIColor(rgba: "#ffa500ff"))
    }

    /// Light => #fa9781ff, Dark => #8a4a3cff
    static var common_orange9_color: UIColor {
        getDynamicColor("common_orange9_color", ["#fa9781ff", "#8a4a3cff"], UIColor(rgba: "#fa9781ff"))
    }

    /// Light => #facd59ff, Dark => #997e38ff
    static var common_yellow_prior_color: UIColor {
        getDynamicColor("common_yellow_prior_color", ["#facd59ff", "#997e38ff"], UIColor(rgba: "#facd59ff"))
    }

    /// Light => #f85e5eff, Dark => #9c2a2aff
    static var common_red3_color: UIColor {
        getDynamicColor("common_red3_color", ["#f85e5eff", "#9c2a2aff"], UIColor(rgba: "#f85e5eff"))
    }

    /// Light => #fef2f2ff, Dark => #512222ff
    static var common_red4_color: UIColor {
        getDynamicColor("common_red4_color", ["#fef2f2ff", "#512222ff"], UIColor(rgba: "#fef2f2ff"))
    }

    /// Light => #d42f2fff, Dark => #f89393ff
    static var common_red5_color: UIColor {
        getDynamicColor("common_red5_color", ["#d42f2fff", "#f89393ff"], UIColor(rgba: "#d42f2fff"))
    }

    /// Light => #d42f2fff, Dark => #d42f2fff
    static var common_red6_color: UIColor {
        getDynamicColor("common_red6_color", ["#d42f2fff", "#d42f2fff"], UIColor(rgba: "#d42f2fff"))
    }

    /// Light => #ff563bcc, Dark => #d04a34ff
    static var common_red7_color: UIColor {
        getDynamicColor("common_red7_color", ["#ff563bcc", "#d04a34ff"], UIColor(rgba: "#ff563bcc"))
    }

    /// Light => #9dadc5ff, Dark => #527fb633
    static var commom_Bluishgrey6_color: UIColor {
        getDynamicColor("commom_Bluishgrey6_color", ["#9dadc5ff", "#527fb633"], UIColor(rgba: "#9dadc5ff"))
    }

    /// Light => #eff0f4ff, Dark => #eff0f41a
    static var common_Bluishgrey8_color: UIColor {
        getDynamicColor("common_Bluishgrey8_color", ["#eff0f4ff", "#eff0f41a"], UIColor(rgba: "#eff0f4ff"))
    }

    /// Light => #5494ffff, Dark => #3669bfff
    static var common_blue6_color: UIColor {
        getDynamicColor("common_blue6_color", ["#5494ffff", "#3669bfff"], UIColor(rgba: "#5494ffff"))
    }

    /// Light => #f1f8ffff, Dark => #142037ff
    static var common_blue7_color: UIColor {
        getDynamicColor("common_blue7_color", ["#f1f8ffff", "#142037ff"], UIColor(rgba: "#f1f8ffff"))
    }

    /// Light => #2c5da7ff, Dark => #99bbffff
    static var common_blue8_color: UIColor {
        getDynamicColor("common_blue8_color", ["#2c5da7ff", "#99bbffff"], UIColor(rgba: "#2c5da7ff"))
    }

    /// Light => #2c5da7ff, Dark => #2c5da7ff
    static var common_blue9_color: UIColor {
        getDynamicColor("common_blue9_color", ["#2c5da7ff", "#2c5da7ff"], UIColor(rgba: "#2c5da7ff"))
    }

    /// Light => #3a97ffff, Dark => #3365b8ff
    static var common_blue10_checkbox_color: UIColor {
        getDynamicColor("common_blue10_checkbox_color", ["#3a97ffff", "#3365b8ff"], UIColor(rgba: "#3a97ffff"))
    }

    /// Light => #bedaf9ff, Dark => #667a90ff
    static var common_blue11_color: UIColor {
        getDynamicColor("common_blue11_color", ["#bedaf9ff", "#667a90ff"], UIColor(rgba: "#bedaf9ff"))
    }

    /// Light => #00bea4ff, Dark => #00a08aff
    static var common_turquoise3_color: UIColor {
        getDynamicColor("common_turquoise3_color", ["#00bea4ff", "#00a08aff"], UIColor(rgba: "#00bea4ff"))
    }

    /// Light => #eafbf7ff, Dark => #112d29ff
    static var common_turquoise4_color: UIColor {
        getDynamicColor("common_turquoise4_color", ["#eafbf7ff", "#112d29ff"], UIColor(rgba: "#eafbf7ff"))
    }

    /// Light => #00836eff, Dark => #77dbcdff
    static var common_turquoise5_color: UIColor {
        getDynamicColor("common_turquoise5_color", ["#00836eff", "#77dbcdff"], UIColor(rgba: "#00836eff"))
    }

    /// Light => #00836eff, Dark => #00836eff
    static var common_turquoise6_color: UIColor {
        getDynamicColor("common_turquoise6_color", ["#00836eff", "#00836eff"], UIColor(rgba: "#00836eff"))
    }

    /// Light => #7f90a9ff, Dark => #4b5e79ff
    static var common_grey1_color: UIColor {
        getDynamicColor("common_grey1_color", ["#7f90a9ff", "#4b5e79ff"], UIColor(rgba: "#7f90a9ff"))
    }

    /// Light => #f1f4f7ff, Dark => #1b2a35ff
    static var common_grey2_color: UIColor {
        getDynamicColor("common_grey2_color", ["#f1f4f7ff", "#1b2a35ff"], UIColor(rgba: "#f1f4f7ff"))
    }

    /// Light => #37668aff, Dark => #bad6eaff
    static var common_grey3_color: UIColor {
        getDynamicColor("common_grey3_color", ["#37668aff", "#bad6eaff"], UIColor(rgba: "#37668aff"))
    }

    /// Light => #37668aff, Dark => #37668aff
    static var common_grey4_color: UIColor {
        getDynamicColor("common_grey4_color", ["#37668aff", "#37668aff"], UIColor(rgba: "#37668aff"))
    }

    /// Light => #06aeeaff, Dark => #008abbff
    static var common_wathet2_color: UIColor {
        getDynamicColor("common_wathet2_color", ["#06aeeaff", "#008abbff"], UIColor(rgba: "#06aeeaff"))
    }

    /// Light => #eff9fcff, Dark => #16323aff
    static var common_wathet3_color: UIColor {
        getDynamicColor("common_wathet3_color", ["#eff9fcff", "#16323aff"], UIColor(rgba: "#eff9fcff"))
    }

    /// Light => #0072adff, Dark => #82d0e6ff
    static var common_wathet4_color: UIColor {
        getDynamicColor("common_wathet4_color", ["#0072adff", "#82d0e6ff"], UIColor(rgba: "#0072adff"))
    }

    /// Light => #0072adff, Dark => #0072adff
    static var common_wathet5_color: UIColor {
        getDynamicColor("common_wathet5_color", ["#0072adff", "#0072adff"], UIColor(rgba: "#0072adff"))
    }

    /// Light => #48b855ff, Dark => #3c9446ff
    static var common_green2_color: UIColor {
        getDynamicColor("common_green2_color", ["#48b855ff", "#3c9446ff"], UIColor(rgba: "#48b855ff"))
    }

    /// Light => #ecfaebff, Dark => #173914ff
    static var common_green3_color: UIColor {
        getDynamicColor("common_green3_color", ["#ecfaebff", "#173914ff"], UIColor(rgba: "#ecfaebff"))
    }

    /// Light => #1f8412ff, Dark => #7dcb79ff
    static var common_green4_color: UIColor {
        getDynamicColor("common_green4_color", ["#1f8412ff", "#7dcb79ff"], UIColor(rgba: "#1f8412ff"))
    }

    /// Light => #1f8412ff, Dark => #1f8412ff
    static var common_green5_color: UIColor {
        getDynamicColor("common_green5_color", ["#1f8412ff", "#1f8412ff"], UIColor(rgba: "#1f8412ff"))
    }

    /// Light => #eead07ff, Dark => #b88400ff
    static var common_yellow5_color: UIColor {
        getDynamicColor("common_yellow5_color", ["#eead07ff", "#b88400ff"], UIColor(rgba: "#eead07ff"))
    }

    /// Light => #fcf7e3ff, Dark => #463714ff
    static var common_yellow6_color: UIColor {
        getDynamicColor("common_yellow6_color", ["#fcf7e3ff", "#463714ff"], UIColor(rgba: "#fcf7e3ff"))
    }

    /// Light => #a06800ff, Dark => #d4b076ff
    static var common_yellow7_color: UIColor {
        getDynamicColor("common_yellow7_color", ["#a06800ff", "#d4b076ff"], UIColor(rgba: "#a06800ff"))
    }

    /// Light => #a06800ff, Dark => #a06800ff
    static var common_yellow8_color: UIColor {
        getDynamicColor("common_yellow8_color", ["#a06800ff", "#a06800ff"], UIColor(rgba: "#a06800ff"))
    }

    /// Light => #ee5694ff, Dark => #b63167ff
    static var common_carmine2_color: UIColor {
        getDynamicColor("common_carmine2_color", ["#ee5694ff", "#b63167ff"], UIColor(rgba: "#ee5694ff"))
    }

    /// Light => #fef2f9ff, Dark => #54223cff
    static var common_carmine3_color: UIColor {
        getDynamicColor("common_carmine3_color", ["#fef2f9ff", "#54223cff"], UIColor(rgba: "#fef2f9ff"))
    }

    /// Light => #a21e67ff, Dark => #ec82baff
    static var common_carmine4_color: UIColor {
        getDynamicColor("common_carmine4_color", ["#a21e67ff", "#ec82baff"], UIColor(rgba: "#a21e67ff"))
    }

    /// Light => #a21e67ff, Dark => #a21e67ff
    static var common_carmine5_color: UIColor {
        getDynamicColor("common_carmine5_color", ["#a21e67ff", "#a21e67ff"], UIColor(rgba: "#a21e67ff"))
    }

    /// Light => #cc5fd3ff, Dark => #892b8fff
    static var common_violet2_color: UIColor {
        getDynamicColor("common_violet2_color", ["#cc5fd3ff", "#892b8fff"], UIColor(rgba: "#cc5fd3ff"))
    }

    /// Light => #fbf2fbff, Dark => #461b46ff
    static var common_violet3_color: UIColor {
        getDynamicColor("common_violet3_color", ["#fbf2fbff", "#461b46ff"], UIColor(rgba: "#fbf2fbff"))
    }

    /// Light => #922592ff, Dark => #ea9aeaff
    static var common_violet4_color: UIColor {
        getDynamicColor("common_violet4_color", ["#922592ff", "#ea9aeaff"], UIColor(rgba: "#922592ff"))
    }

    /// Light => #922592ff, Dark => #922592ff
    static var common_violet5_color: UIColor {
        getDynamicColor("common_violet5_color", ["#922592ff", "#922592ff"], UIColor(rgba: "#922592ff"))
    }

    /// Light => #9572e8ff, Dark => #6540a8ff
    static var common_purple2_color: UIColor {
        getDynamicColor("common_purple2_color", ["#9572e8ff", "#6540a8ff"], UIColor(rgba: "#9572e8ff"))
    }

    /// Light => #f8f4ffff, Dark => #25153eff
    static var common_purple3_color: UIColor {
        getDynamicColor("common_purple3_color", ["#f8f4ffff", "#25153eff"], UIColor(rgba: "#f8f4ffff"))
    }

    /// Light => #6638b4ff, Dark => #ba90ffff
    static var common_purple4_color: UIColor {
        getDynamicColor("common_purple4_color", ["#6638b4ff", "#ba90ffff"], UIColor(rgba: "#6638b4ff"))
    }

    /// Light => #6638b4ff, Dark => #6638b4ff
    static var common_purple5_color: UIColor {
        getDynamicColor("common_purple5_color", ["#6638b4ff", "#6638b4ff"], UIColor(rgba: "#6638b4ff"))
    }

    /// Light => #7881e6ff, Dark => #474fadff
    static var common_indigo2_color: UIColor {
        getDynamicColor("common_indigo2_color", ["#7881e6ff", "#474fadff"], UIColor(rgba: "#7881e6ff"))
    }

    /// Light => #f4f5fdff, Dark => #1d2042ff
    static var common_indigo3_color: UIColor {
        getDynamicColor("common_indigo3_color", ["#f4f5fdff", "#1d2042ff"], UIColor(rgba: "#f4f5fdff"))
    }

    /// Light => #424ab4ff, Dark => #a6adfcff
    static var common_indigo4_color: UIColor {
        getDynamicColor("common_indigo4_color", ["#424ab4ff", "#a6adfcff"], UIColor(rgba: "#424ab4ff"))
    }

    /// Light => #424ab4ff, Dark => #424ab4ff
    static var common_indigo5_color: UIColor {
        getDynamicColor("common_indigo5_color", ["#424ab4ff", "#424ab4ff"], UIColor(rgba: "#424ab4ff"))
    }

    /// Light => #aa7d65ff, Dark => #7e5744ff
    static var common_brown1_color: UIColor {
        getDynamicColor("common_brown1_color", ["#aa7d65ff", "#7e5744ff"], UIColor(rgba: "#aa7d65ff"))
    }

    /// Light => #f8f4f2ff, Dark => #2c1d15ff
    static var common_brown2_color: UIColor {
        getDynamicColor("common_brown2_color", ["#f8f4f2ff", "#2c1d15ff"], UIColor(rgba: "#f8f4f2ff"))
    }

    /// Light => #8e4f2eff, Dark => #ddc2b5ff
    static var common_brown3_color: UIColor {
        getDynamicColor("common_brown3_color", ["#8e4f2eff", "#ddc2b5ff"], UIColor(rgba: "#8e4f2eff"))
    }

    /// Light => #8e4f2eff, Dark => #8e4f2eff
    static var common_brown4_color: UIColor {
        getDynamicColor("common_brown4_color", ["#8e4f2eff", "#8e4f2eff"], UIColor(rgba: "#8e4f2eff"))
    }

    /// Light => #f5f6faff, Dark => #0e0e0eff
    static var common_bg21_color: UIColor {
        getDynamicColor("common_bg21_color", ["#f5f6faff", "#0e0e0eff"], UIColor(rgba: "#f5f6faff"))
    }

    /// Light => #b9b9b9ff, Dark => #3a3a3aff
    static var common_bg22_color: UIColor {
        getDynamicColor("common_bg22_color", ["#b9b9b9ff", "#3a3a3aff"], UIColor(rgba: "#b9b9b9ff"))
    }

    /// Light => #ffffffe6, Dark => #1a1a1ae6
    static var common_bg24_color: UIColor {
        getDynamicColor("common_bg24_color", ["#ffffffe6", "#1a1a1ae6"], UIColor(rgba: "#ffffffe6"))
    }

    /// Light => #f1f1f1ff, Dark => #3e3e3efc
    static var common_bg26_color: UIColor {
        getDynamicColor("common_bg26_color", ["#f1f1f1ff", "#3e3e3efc"], UIColor(rgba: "#f1f1f1ff"))
    }

    /// Light => #ffffffff, Dark => #1a1a1aff
    static var common_bg_mask3_color: UIColor {
        getDynamicColor("common_bg_mask3_color", ["#ffffffff", "#1a1a1aff"], UIColor(rgba: "#ffffffff"))
    }

    /// Light => #ffffff66, Dark => #1a1a1a66
    static var common_bg_mask4_color: UIColor {
        getDynamicColor("common_bg_mask4_color", ["#ffffff66", "#1a1a1a66"], UIColor(rgba: "#ffffff66"))
    }

    /// Light => #fd7d48ff, Dark => #fd7d48ff
    static var common_orange10_color: UIColor {
        getDynamicColor("common_orange10_color", ["#fd7d48ff", "#fd7d48ff"], UIColor(rgba: "#fd7d48ff"))
    }

    /// Light => #eff5f9ff, Dark => #3a97ff1a
    static var common_Bluishgrey9_color: UIColor {
        getDynamicColor("common_Bluishgrey9_color", ["#eff5f9ff", "#3a97ff1a"], UIColor(rgba: "#eff5f9ff"))
    }

    /// Light => #3e7efbff, Dark => #3e7efbff
    static var common_blue12_color: UIColor {
        getDynamicColor("common_blue12_color", ["#3e7efbff", "#3e7efbff"], UIColor(rgba: "#3e7efbff"))
    }

    /// Light => #7a8aa9ff, Dark => #7a8aa9ff
    static var common_grey10_color: UIColor {
        getDynamicColor("common_grey10_color", ["#7a8aa9ff", "#7a8aa9ff"], UIColor(rgba: "#7a8aa9ff"))
    }

    /// Light => #08c2a9ff, Dark => #08c2a9ff
    static var common_turquoise9_color: UIColor {
        getDynamicColor("common_turquoise9_color", ["#08c2a9ff", "#08c2a9ff"], UIColor(rgba: "#08c2a9ff"))
    }

    /// Light => #39b44fff, Dark => #39b44fff
    static var common_green6_color: UIColor {
        getDynamicColor("common_green6_color", ["#39b44fff", "#39b44fff"], UIColor(rgba: "#39b44fff"))
    }

    /// Light => #fdb706ff, Dark => #fdb706ff
    static var common_yellow9_color: UIColor {
        getDynamicColor("common_yellow9_color", ["#fdb706ff", "#fdb706ff"], UIColor(rgba: "#fdb706ff"))
    }

    /// Light => #f26199ff, Dark => #f26199ff
    static var common_carmine6_color: UIColor {
        getDynamicColor("common_carmine6_color", ["#f26199ff", "#f26199ff"], UIColor(rgba: "#f26199ff"))
    }

    /// Light => #8f68d5ff, Dark => #8f68d5ff
    static var common_purple6_color: UIColor {
        getDynamicColor("common_purple6_color", ["#8f68d5ff", "#8f68d5ff"], UIColor(rgba: "#8f68d5ff"))
    }

    /// Light => #ffffffcc, Dark => #ffffff0a
    static var common_bg14_color: UIColor {
        getDynamicColor("common_bg14_color", ["#ffffffcc", "#ffffff0a"], UIColor(rgba: "#ffffffcc"))
    }

    /// Light => #fbfbfbff, Dark => #1d1d1dff
    static var common_bg16_color: UIColor {
        getDynamicColor("common_bg16_color", ["#fbfbfbff", "#1d1d1dff"], UIColor(rgba: "#fbfbfbff"))
    }

    /// Light => #fbfbfbff, Dark => #141414ff
    static var common_bg17_color: UIColor {
        getDynamicColor("common_bg17_color", ["#fbfbfbff", "#141414ff"], UIColor(rgba: "#fbfbfbff"))
    }

    /// Light => #ffffffff, Dark => #2a2a2aff
    static var common_bg20_color: UIColor {
        getDynamicColor("common_bg20_color", ["#ffffffff", "#2a2a2aff"], UIColor(rgba: "#ffffffff"))
    }

    /// Light => #1f1f2533, Dark => #00000033
    static var common_shadow2_color: UIColor {
        getDynamicColor("common_shadow2_color", ["#1f1f2533", "#00000033"], UIColor(rgba: "#1f1f2533"))
    }

    /// Light => #ffffff1f, Dark => #ffffff1f
    static var common_line5_color: UIColor {
        getDynamicColor("common_line5_color", ["#ffffff1f", "#ffffff1f"], UIColor(rgba: "#ffffff1f"))
    }

    /// Light => #111111ff, Dark => #fffffff2
    static var common_level7_color: UIColor {
        getDynamicColor("common_level7_color", ["#111111ff", "#fffffff2"], UIColor(rgba: "#111111ff"))
    }

    /// Light => #ff5833ff, Dark => #d53613ff
    static var common_level_alert_color: UIColor {
        getDynamicColor("common_level_alert_color", ["#ff5833ff", "#d53613ff"], UIColor(rgba: "#ff5833ff"))
    }

    /// Light => #a4a4a4ff, Dark => #ffffff73
    static var common_level8_color: UIColor {
        getDynamicColor("common_level8_color", ["#a4a4a4ff", "#ffffff73"], UIColor(rgba: "#a4a4a4ff"))
    }

    /// Light => #505050ff, Dark => #ffffff99
    static var common_level9_color: UIColor {
        getDynamicColor("common_level9_color", ["#505050ff", "#ffffff99"], UIColor(rgba: "#505050ff"))
    }

    /// Light => #b2b2b2ff, Dark => #ffffff59
    static var common_level10_color: UIColor {
        getDynamicColor("common_level10_color", ["#b2b2b2ff", "#ffffff59"], UIColor(rgba: "#b2b2b2ff"))
    }

    /// Light => #000000ff, Dark => #ffffffff
    static var common_level11_color: UIColor {
        getDynamicColor("common_level11_color", ["#000000ff", "#ffffffff"], UIColor(rgba: "#000000ff"))
    }

    /// Light => #fd7443ff, Dark => #d15731ff
    static var common_level12_color: UIColor {
        getDynamicColor("common_level12_color", ["#fd7443ff", "#d15731ff"], UIColor(rgba: "#fd7443ff"))
    }

    /// Light => #fd762cff, Dark => #d15731ff
    static var common_level13_color: UIColor {
        getDynamicColor("common_level13_color", ["#fd762cff", "#d15731ff"], UIColor(rgba: "#fd762cff"))
    }

    /// Light => #252629ff, Dark => #fffffffc
    static var common_level14_color: UIColor {
        getDynamicColor("common_level14_color", ["#252629ff", "#fffffffc"], UIColor(rgba: "#252629ff"))
    }

    /// Light => #fd7443ff, Dark => #d15731ff
    static var common_line6_color: UIColor {
        getDynamicColor("common_line6_color", ["#fd7443ff", "#d15731ff"], UIColor(rgba: "#fd7443ff"))
    }

    /// Light => #dadadaff, Dark => #ffffff26
    static var common_line7_color: UIColor {
        getDynamicColor("common_line7_color", ["#dadadaff", "#ffffff26"], UIColor(rgba: "#dadadaff"))
    }

    /// Light => #dededeff, Dark => #ffffff33
    static var common_line8_color: UIColor {
        getDynamicColor("common_line8_color", ["#dededeff", "#ffffff33"], UIColor(rgba: "#dededeff"))
    }

    /// Light => #eaeaeaff, Dark => #ffffff26
    static var common_line9_color: UIColor {
        getDynamicColor("common_line9_color", ["#eaeaeaff", "#ffffff26"], UIColor(rgba: "#eaeaeaff"))
    }

    /// Light => #c0c0c0ff, Dark => #ffffff33
    static var common_line10_color: UIColor {
        getDynamicColor("common_line10_color", ["#c0c0c0ff", "#ffffff33"], UIColor(rgba: "#c0c0c0ff"))
    }

    /// Light => #f3f3f3ff, Dark => #2a2a2aff
    static var common_line11_color: UIColor {
        getDynamicColor("common_line11_color", ["#f3f3f3ff", "#2a2a2aff"], UIColor(rgba: "#f3f3f3ff"))
    }

    /// Light => #f2f2f7ff, Dark => #1a1a1aff
    static var common_bg23_color: UIColor {
        getDynamicColor("common_bg23_color", ["#f2f2f7ff", "#1a1a1aff"], UIColor(rgba: "#f2f2f7ff"))
    }

    /// Light => #222525ff, Dark => #d15731ff
    static var common_bg25_color: UIColor {
        getDynamicColor("common_bg25_color", ["#222525ff", "#d15731ff"], UIColor(rgba: "#222525ff"))
    }

    /// Light => #f34c42ff, Dark => #bd3936ff
    static var common_red8_color: UIColor {
        getDynamicColor("common_red8_color", ["#f34c42ff", "#bd3936ff"], UIColor(rgba: "#f34c42ff"))
    }

    /// Light => #ff5133ff, Dark => #e54320ff
    static var common_red9_color: UIColor {
        getDynamicColor("common_red9_color", ["#ff5133ff", "#e54320ff"], UIColor(rgba: "#ff5133ff"))
    }

    /// Light => #ff4133ff, Dark => #d33632ff
    static var common_red10_color: UIColor {
        getDynamicColor("common_red10_color", ["#ff4133ff", "#d33632ff"], UIColor(rgba: "#ff4133ff"))
    }

    /// Light => #fef0f1ff, Dark => #d157311a
    static var common_red11_color: UIColor {
        getDynamicColor("common_red11_color", ["#fef0f1ff", "#d157311a"], UIColor(rgba: "#fef0f1ff"))
    }

    /// Light => #ff563bff, Dark => #d84128ff
    static var common_red12_color: UIColor {
        getDynamicColor("common_red12_color", ["#ff563bff", "#d84128ff"], UIColor(rgba: "#ff563bff"))
    }

    /// Light => #a8acb5ff, Dark => #444850ff
    static var common_Bluishgrey7_color: UIColor {
        getDynamicColor("common_Bluishgrey7_color", ["#a8acb5ff", "#444850ff"], UIColor(rgba: "#a8acb5ff"))
    }

    /// Light => #2cbfa4ff, Dark => #18a58bff
    static var common_turquoise7_color: UIColor {
        getDynamicColor("common_turquoise7_color", ["#2cbfa4ff", "#18a58bff"], UIColor(rgba: "#2cbfa4ff"))
    }

    /// Light => #2ecda4ff, Dark => #18be9fff
    static var common_turquoise8_color: UIColor {
        getDynamicColor("common_turquoise8_color", ["#2ecda4ff", "#18be9fff"], UIColor(rgba: "#2ecda4ff"))
    }

    /// Light => #71757dff, Dark => #b9babcff
    static var common_grey5_color: UIColor {
        getDynamicColor("common_grey5_color", ["#71757dff", "#b9babcff"], UIColor(rgba: "#71757dff"))
    }

    /// Light => #bbbbbbff, Dark => #ffffff66
    static var common_grey6_color: UIColor {
        getDynamicColor("common_grey6_color", ["#bbbbbbff", "#ffffff66"], UIColor(rgba: "#bbbbbbff"))
    }

    /// Light => #616061ff, Dark => #ffffff73
    static var common_grey7_color: UIColor {
        getDynamicColor("common_grey7_color", ["#616061ff", "#ffffff73"], UIColor(rgba: "#616061ff"))
    }

    /// Light => #c2c2c2ff, Dark => #ffffff40
    static var connom_grey8_color: UIColor {
        getDynamicColor("connom_grey8_color", ["#c2c2c2ff", "#ffffff40"], UIColor(rgba: "#c2c2c2ff"))
    }

    /// Light => #c0c0c0ff, Dark => #ffffff33
    static var common_grey9_color: UIColor {
        getDynamicColor("common_grey9_color", ["#c0c0c0ff", "#ffffff33"], UIColor(rgba: "#c0c0c0ff"))
    }

    /// Light => #9699a5ff, Dark => #ffffff80
    static var common_level15_color: UIColor {
        getDynamicColor("common_level15_color", ["#9699a5ff", "#ffffff80"], UIColor(rgba: "#9699a5ff"))
    }

    /// Light => #f7f7f7ff, Dark => #262626fc
    static var common_bg_touch3_color: UIColor {
        getDynamicColor("common_bg_touch3_color", ["#f7f7f7ff", "#262626fc"], UIColor(rgba: "#f7f7f7ff"))
    }

    /// Light => #e0e0e0ff, Dark => #ffffff1f
    static var common_line12_color: UIColor {
        getDynamicColor("common_line12_color", ["#e0e0e0ff", "#ffffff1f"], UIColor(rgba: "#e0e0e0ff"))
    }

    /// Light => #eeeeeeff, Dark => #1a1a1aff
    static var common_bg27_color: UIColor {
        getDynamicColor("common_bg27_color", ["#eeeeeeff", "#1a1a1aff"], UIColor(rgba: "#eeeeeeff"))
    }

    /// Light => #ffffffff, Dark => #ffffff99
    static var common_level16_color: UIColor {
        getDynamicColor("common_level16_color", ["#ffffffff", "#ffffff99"], UIColor(rgba: "#ffffffff"))
    }

    /// Light => #bbbbbbff, Dark => #ffffff66
    static var common_icon1_color: UIColor {
        getDynamicColor("common_icon1_color", ["#bbbbbbff", "#ffffff66"], UIColor(rgba: "#bbbbbbff"))
    }

    /// Light => #282a30ff, Dark => #ffffffe6
    static var common_icon2_color: UIColor {
        getDynamicColor("common_icon2_color", ["#282a30ff", "#ffffffe6"], UIColor(rgba: "#282a30ff"))
    }

    /// Light => #aeaeaeff, Dark => #ffffff6b
    static var common_level17_color: UIColor {
        getDynamicColor("common_level17_color", ["#aeaeaeff", "#ffffff6b"], UIColor(rgba: "#aeaeaeff"))
    }

    /// Light => #ffffffff, Dark => #ffffffff
    static var common_icon3_color: UIColor {
        getDynamicColor("common_icon3_color", ["#ffffffff", "#ffffffff"], UIColor(rgba: "#ffffffff"))
    }

    /// Light => #5f6972ff, Dark => #ffffffb3
    static var common_icon4_color: UIColor {
        getDynamicColor("common_icon4_color", ["#5f6972ff", "#ffffffb3"], UIColor(rgba: "#5f6972ff"))
    }

    /// Light => #909090ff, Dark => #ffffff80
    static var common_icon5_color: UIColor {
        getDynamicColor("common_icon5_color", ["#909090ff", "#ffffff80"], UIColor(rgba: "#909090ff"))
    }

    /// Light => #888888ff, Dark => #ffffff73
    static var common_icon6_color: UIColor {
        getDynamicColor("common_icon6_color", ["#888888ff", "#ffffff73"], UIColor(rgba: "#888888ff"))
    }

    /// Light => #b3b7bdff, Dark => #ffffff80
    static var common_icon7_color: UIColor {
        getDynamicColor("common_icon7_color", ["#b3b7bdff", "#ffffff80"], UIColor(rgba: "#b3b7bdff"))
    }

    /// Light => #bbbbbbff, Dark => #ffffff66
    static var common_level18_color: UIColor {
        getDynamicColor("common_level18_color", ["#bbbbbbff", "#ffffff66"], UIColor(rgba: "#bbbbbbff"))
    }

    /// Light => #666666ff, Dark => #ffffffe6
    static var common_level19_color: UIColor {
        getDynamicColor("common_level19_color", ["#666666ff", "#ffffffe6"], UIColor(rgba: "#666666ff"))
    }

    /// Light => #bbbbbbff, Dark => #ffffff80
    static var common_level20_color: UIColor {
        getDynamicColor("common_level20_color", ["#bbbbbbff", "#ffffff80"], UIColor(rgba: "#bbbbbbff"))
    }

    /// Light => #e6e6e6ff, Dark => #ffffff33
    static var common_line13_color: UIColor {
        getDynamicColor("common_line13_color", ["#e6e6e6ff", "#ffffff33"], UIColor(rgba: "#e6e6e6ff"))
    }

    /// Light => #fbfbfbff, Dark => #ffffffcc
    static var common_level21_color: UIColor {
        getDynamicColor("common_level21_color", ["#fbfbfbff", "#ffffffcc"], UIColor(rgba: "#fbfbfbff"))
    }

    /// Light => #ffffffcc, Dark => #ffffffa8
    static var common_level22_color: UIColor {
        getDynamicColor("common_level22_color", ["#ffffffcc", "#ffffffa8"], UIColor(rgba: "#ffffffcc"))
    }

    /// Light => #ddddddff, Dark => #ffffff40
    static var common_bg28_color: UIColor {
        getDynamicColor("common_bg28_color", ["#ddddddff", "#ffffff40"], UIColor(rgba: "#ddddddff"))
    }

    /// Light => #ee444cff, Dark => #d75548ff
    static var common_red13_color: UIColor {
        getDynamicColor("common_red13_color", ["#ee444cff", "#d75548ff"], UIColor(rgba: "#ee444cff"))
    }

    /// Light => #a6721c99, Dark => #d09e39cc
    static var common_yellow10_color: UIColor {
        getDynamicColor("common_yellow10_color", ["#a6721c99", "#d09e39cc"], UIColor(rgba: "#a6721c99"))
    }

    /// Light => #ffecccff, Dark => #f3d198ff
    static var common_yellow11_color: UIColor {
        getDynamicColor("common_yellow11_color", ["#ffecccff", "#f3d198ff"], UIColor(rgba: "#ffecccff"))
    }

    /// Light => #f7dcb1ff, Dark => #f7dcb1ff
    static var common_yellow12_color: UIColor {
        getDynamicColor("common_yellow12_color", ["#f7dcb1ff", "#f7dcb1ff"], UIColor(rgba: "#f7dcb1ff"))
    }

    /// Light => #f1cd9299, Dark => #66513099
    static var common_yellow13_color: UIColor {
        getDynamicColor("common_yellow13_color", ["#f1cd9299", "#66513099"], UIColor(rgba: "#f1cd9299"))
    }

    /// Light => #f58f93ff, Dark => #e18076ff
    static var common_red14_color: UIColor {
        getDynamicColor("common_red14_color", ["#f58f93ff", "#e18076ff"], UIColor(rgba: "#f58f93ff"))
    }

    /// Light => #fff5f2ff, Dark => #d1573129
    static var common_orange11_color: UIColor {
        getDynamicColor("common_orange11_color", ["#fff5f2ff", "#d1573129"], UIColor(rgba: "#fff5f2ff"))
    }

    /// Light => #fefefeff, Dark => #262626fa
    static var common_bg29_color: UIColor {
        getDynamicColor("common_bg29_color", ["#fefefeff", "#262626fa"], UIColor(rgba: "#fefefeff"))
    }

    /// Light => #f7f7faff, Dark => #262628ff
    static var common_bluishgrey10_color: UIColor {
        getDynamicColor("common_bluishgrey10_color", ["#f7f7faff", "#262628ff"], UIColor(rgba: "#f7f7faff"))
    }

    /// Light => #ffffffff, Dark => #202020ff
    static var common_bg30_color: UIColor {
        getDynamicColor("common_bg30_color", ["#ffffffff", "#202020ff"], UIColor(rgba: "#ffffffff"))
    }

    /// Light => #f7f7faff, Dark => #3c3c3eff
    static var common_bg31_color: UIColor {
        getDynamicColor("common_bg31_color", ["#f7f7faff", "#3c3c3eff"], UIColor(rgba: "#f7f7faff"))
    }

    /// Light => #333333ff, Dark => #ffffffcc
    static var common_level23_color: UIColor {
        getDynamicColor("common_level23_color", ["#333333ff", "#ffffffcc"], UIColor(rgba: "#333333ff"))
    }

    /// Light => #00a59fff, Dark => #00a59fff
    static var common_turquoise10_color: UIColor {
        getDynamicColor("common_turquoise10_color", ["#00a59fff", "#00a59fff"], UIColor(rgba: "#00a59fff"))
    }

    /// Light => #00a59f14, Dark => #00a59f1f
    static var common_turquoise11_color: UIColor {
        getDynamicColor("common_turquoise11_color", ["#00a59f14", "#00a59f1f"], UIColor(rgba: "#00a59f14"))
    }

    /// Light => #ff9520ff, Dark => #ff9520ff
    static var common_orange12_color: UIColor {
        getDynamicColor("common_orange12_color", ["#ff9520ff", "#ff9520ff"], UIColor(rgba: "#ff9520ff"))
    }

    /// Light => #ff952014, Dark => #ff95201f
    static var common_orange13_color: UIColor {
        getDynamicColor("common_orange13_color", ["#ff952014", "#ff95201f"], UIColor(rgba: "#ff952014"))
    }

    /// Light => #fd74430d, Dark => #d157310d
    static var common_orange14_color: UIColor {
        getDynamicColor("common_orange14_color", ["#fd74430d", "#d157310d"], UIColor(rgba: "#fd74430d"))
    }

    /// Light => #222525e6, Dark => #d15731e6
    static var common_orange15_color: UIColor {
        getDynamicColor("common_orange15_color", ["#222525e6", "#d15731e6"], UIColor(rgba: "#222525e6"))
    }

    /// Light => #5b5b5bff, Dark => #ffffffe6
    static var common_icon8_color: UIColor {
        getDynamicColor("common_icon8_color", ["#5b5b5bff", "#ffffffe6"], UIColor(rgba: "#5b5b5bff"))
    }

    /// Light => #86909cff, Dark => #ffffff80
    static var common_level24_color: UIColor {
        getDynamicColor("common_level24_color", ["#86909cff", "#ffffff80"], UIColor(rgba: "#86909cff"))
    }

    /// Light => #96989eff, Dark => #ffffff99
    static var common_bluishgrey11_color: UIColor {
        getDynamicColor("common_bluishgrey11_color", ["#96989eff", "#ffffff99"], UIColor(rgba: "#96989eff"))
    }

    /// Light => #fd744333, Dark => #d1573133
    static var common_orange16_color: UIColor {
        getDynamicColor("common_orange16_color", ["#fd744333", "#d1573133"], UIColor(rgba: "#fd744333"))
    }

    /// Light => #ffe7ddff, Dark => #441c0cff
    static var common_line14_color: UIColor {
        getDynamicColor("common_line14_color", ["#ffe7ddff", "#441c0cff"], UIColor(rgba: "#ffe7ddff"))
    }

    /// Light => #ffffff00, Dark => #00000000
    static var common_clear_color: UIColor {
        getDynamicColor("common_clear_color", ["#ffffff00", "#00000000"], UIColor(rgba: "#ffffff00"))
    }

    /// Light => #bbbabbff, Dark => #ffffff73
    static var common_icon9_color: UIColor {
        getDynamicColor("common_icon9_color", ["#bbbabbff", "#ffffff73"], UIColor(rgba: "#bbbabbff"))
    }

    /// Light => #f9f9f9ff, Dark => #202020ff
    static var common_bg32_color: UIColor {
        getDynamicColor("common_bg32_color", ["#f9f9f9ff", "#202020ff"], UIColor(rgba: "#f9f9f9ff"))
    }

    /// Light => #333333ff, Dark => #ffffffe6
    static var common_icon10_color: UIColor {
        getDynamicColor("common_icon10_color", ["#333333ff", "#ffffffe6"], UIColor(rgba: "#333333ff"))
    }

    /// Light => #cdcdcdff, Dark => #393939ff
    static var common_icon11_color: UIColor {
        getDynamicColor("common_icon11_color", ["#cdcdcdff", "#393939ff"], UIColor(rgba: "#cdcdcdff"))
    }

    /// Light => #e6e9eeff, Dark => #27282bff
    static var common_bluishgrey12_color: UIColor {
        getDynamicColor("common_bluishgrey12_color", ["#e6e9eeff", "#27282bff"], UIColor(rgba: "#e6e9eeff"))
    }

    /// Light => #86898cff, Dark => #bfc5cbff
    static var common_level25_color: UIColor {
        getDynamicColor("common_level25_color", ["#86898cff", "#bfc5cbff"], UIColor(rgba: "#86898cff"))
    }

    /// Light => #ffede4ff, Dark => #261c14ff
    static var common_orange17_color: UIColor {
        getDynamicColor("common_orange17_color", ["#ffede4ff", "#261c14ff"], UIColor(rgba: "#ffede4ff"))
    }

    /// Light => #c65228ff, Dark => #ae4e2cff
    static var common_level26_color: UIColor {
        getDynamicColor("common_level26_color", ["#c65228ff", "#ae4e2cff"], UIColor(rgba: "#c65228ff"))
    }

    /// Light => #f2fefbeb, Dark => #092521e6
    static var common_turquoise12_color: UIColor {
        getDynamicColor("common_turquoise12_color", ["#f2fefbeb", "#092521e6"], UIColor(rgba: "#f2fefbeb"))
    }

    /// Light => #1cb492ff, Dark => #60dfc8ff
    static var common_turquoise13_color: UIColor {
        getDynamicColor("common_turquoise13_color", ["#1cb492ff", "#60dfc8ff"], UIColor(rgba: "#1cb492ff"))
    }

    /// Light => #60d2abff, Dark => #00a08aff
    static var common_line15_color: UIColor {
        getDynamicColor("common_line15_color", ["#60d2abff", "#00a08aff"], UIColor(rgba: "#60d2abff"))
    }

    /// Light => #ff8d65ff, Dark => #d15731ff
    static var common_line16_color: UIColor {
        getDynamicColor("common_line16_color", ["#ff8d65ff", "#d15731ff"], UIColor(rgba: "#ff8d65ff"))
    }

    /// Light => #ffefebe6, Dark => #4f2a0ce6
    static var common_orange18_color: UIColor {
        getDynamicColor("common_orange18_color", ["#ffefebe6", "#4f2a0ce6"], UIColor(rgba: "#ffefebe6"))
    }

    /// Light => #fd7443ff, Dark => #fa9875ff
    static var common_orange19_color: UIColor {
        getDynamicColor("common_orange19_color", ["#fd7443ff", "#fa9875ff"], UIColor(rgba: "#fd7443ff"))
    }

    /// Light => #f7f7f7ff, Dark => #1f1f1fff
    static var common_bg33_color: UIColor {
        getDynamicColor("common_bg33_color", ["#f7f7f7ff", "#1f1f1fff"], UIColor(rgba: "#f7f7f7ff"))
    }
}

// MARK: - CGColor
public extension CGColor {
    
    /// Light => #333333ff, Dark => #ffffffe6
    static var common_level1_color: CGColor {
        getDynamicColor("common_level1_color", ["#333333ff", "#ffffffe6"], UIColor(rgba: "#333333ff").cgColor)
    }

    /// Light => #666666ff, Dark => #ffffff99
    static var common_level2_color: CGColor {
        getDynamicColor("common_level2_color", ["#666666ff", "#ffffff99"], UIColor(rgba: "#666666ff").cgColor)
    }

    /// Light => #999999ff, Dark => #ffffff80
    static var common_level3_color: CGColor {
        getDynamicColor("common_level3_color", ["#999999ff", "#ffffff80"], UIColor(rgba: "#999999ff").cgColor)
    }

    /// Light => #abababff, Dark => #ffffff66
    static var common_level4_color: CGColor {
        getDynamicColor("common_level4_color", ["#abababff", "#ffffff66"], UIColor(rgba: "#abababff").cgColor)
    }

    /// Light => #bbbbbbff, Dark => #ffffff40
    static var common_level5_color: CGColor {
        getDynamicColor("common_level5_color", ["#bbbbbbff", "#ffffff40"], UIColor(rgba: "#bbbbbbff").cgColor)
    }

    /// Light => #ffffffff, Dark => #ffffffeb
    static var common_level6_color: CGColor {
        getDynamicColor("common_level6_color", ["#ffffffff", "#ffffffeb"], UIColor(rgba: "#ffffffff").cgColor)
    }

    /// Light => #e2e2e233, Dark => #e2e2e20a
    static var common_level_watermark_color: CGColor {
        getDynamicColor("common_level_watermark_color", ["#e2e2e233", "#e2e2e20a"], UIColor(rgba: "#e2e2e233").cgColor)
    }

    /// Light => #e8e8e8ff, Dark => #ffffff1f
    static var common_line1_color: CGColor {
        getDynamicColor("common_line1_color", ["#e8e8e8ff", "#ffffff1f"], UIColor(rgba: "#e8e8e8ff").cgColor)
    }

    /// Light => #eeeeeeff, Dark => #ffffff14
    static var common_line2_color: CGColor {
        getDynamicColor("common_line2_color", ["#eeeeeeff", "#ffffff14"], UIColor(rgba: "#eeeeeeff").cgColor)
    }

    /// Light => #999999ff, Dark => #ffffff66
    static var common_line3_color: CGColor {
        getDynamicColor("common_line3_color", ["#999999ff", "#ffffff66"], UIColor(rgba: "#999999ff").cgColor)
    }

    /// Light => #ffffffff, Dark => #1a1a1afc
    static var common_line4_color: CGColor {
        getDynamicColor("common_line4_color", ["#ffffffff", "#1a1a1afc"], UIColor(rgba: "#ffffffff").cgColor)
    }

    /// Light => #f7f7f7ff, Dark => #0e0e0eff
    static var common_bg1_color: CGColor {
        getDynamicColor("common_bg1_color", ["#f7f7f7ff", "#0e0e0eff"], UIColor(rgba: "#f7f7f7ff").cgColor)
    }

    /// Light => #ffffffff, Dark => #1a1a1aff
    static var common_bg2_color: CGColor {
        getDynamicColor("common_bg2_color", ["#ffffffff", "#1a1a1aff"], UIColor(rgba: "#ffffffff").cgColor)
    }

    /// Light => #f7f7f7ff, Dark => #262626fc
    static var common_bg3_color: CGColor {
        getDynamicColor("common_bg3_color", ["#f7f7f7ff", "#262626fc"], UIColor(rgba: "#f7f7f7ff").cgColor)
    }

    /// Light => #f3f3f3ff, Dark => #2a2a2aff
    static var common_bg4_color: CGColor {
        getDynamicColor("common_bg4_color", ["#f3f3f3ff", "#2a2a2aff"], UIColor(rgba: "#f3f3f3ff").cgColor)
    }

    /// Light => #e8e8e8ff, Dark => #ffffff40
    static var common_bg5_color: CGColor {
        getDynamicColor("common_bg5_color", ["#e8e8e8ff", "#ffffff40"], UIColor(rgba: "#e8e8e8ff").cgColor)
    }

    /// Light => #ffffffff, Dark => #262626ff
    static var common_bg6_color: CGColor {
        getDynamicColor("common_bg6_color", ["#ffffffff", "#262626ff"], UIColor(rgba: "#ffffffff").cgColor)
    }

    /// Light => #ffffffff, Dark => #3e3e3eff
    static var common_bg7_color: CGColor {
        getDynamicColor("common_bg7_color", ["#ffffffff", "#3e3e3eff"], UIColor(rgba: "#ffffffff").cgColor)
    }

    /// Light => #333333ff, Dark => #d15731fc
    static var common_bg8_color: CGColor {
        getDynamicColor("common_bg8_color", ["#333333ff", "#d15731fc"], UIColor(rgba: "#333333ff").cgColor)
    }

    /// Light => #343434ff, Dark => #3e3e3eff
    static var common_bg9_color: CGColor {
        getDynamicColor("common_bg9_color", ["#343434ff", "#3e3e3eff"], UIColor(rgba: "#343434ff").cgColor)
    }

    /// Light => #f7f7f7ff, Dark => #1a1a1aff
    static var common_bg11_color: CGColor {
        getDynamicColor("common_bg11_color", ["#f7f7f7ff", "#1a1a1aff"], UIColor(rgba: "#f7f7f7ff").cgColor)
    }

    /// Light => #0000001a, Dark => #ffffff1a
    static var common_bg10_color: CGColor {
        getDynamicColor("common_bg10_color", ["#0000001a", "#ffffff1a"], UIColor(rgba: "#0000001a").cgColor)
    }

    /// Light => #f2f2f2ff, Dark => #ffffff14
    static var common_bg_touch1_color: CGColor {
        getDynamicColor("common_bg_touch1_color", ["#f2f2f2ff", "#ffffff14"], UIColor(rgba: "#f2f2f2ff").cgColor)
    }

    /// Light => #ffffff33, Dark => #00000033
    static var common_bg_touch2_color: CGColor {
        getDynamicColor("common_bg_touch2_color", ["#ffffff33", "#00000033"], UIColor(rgba: "#ffffff33").cgColor)
    }

    /// Light => #00000066, Dark => #00000099
    static var common_bg_mask_color: CGColor {
        getDynamicColor("common_bg_mask_color", ["#00000066", "#00000099"], UIColor(rgba: "#00000066").cgColor)
    }

    /// Light => #ffffff80, Dark => #1a1a1a80
    static var common_bg_mask2_color: CGColor {
        getDynamicColor("common_bg_mask2_color", ["#ffffff80", "#1a1a1a80"], UIColor(rgba: "#ffffff80").cgColor)
    }

    /// Light => #0000001f, Dark => #0000001f
    static var common_shadow1_color: CGColor {
        getDynamicColor("common_shadow1_color", ["#0000001f", "#0000001f"], UIColor(rgba: "#0000001f").cgColor)
    }

    /// Light => #fd7443ff, Dark => #d15731ff
    static var common_orange1_color: CGColor {
        getDynamicColor("common_orange1_color", ["#fd7443ff", "#d15731ff"], UIColor(rgba: "#fd7443ff").cgColor)
    }

    /// Light => #fd744366, Dark => #d1573166
    static var common_orange2_color: CGColor {
        getDynamicColor("common_orange2_color", ["#fd744366", "#d1573166"], UIColor(rgba: "#fd744366").cgColor)
    }

    /// Light => #fd74431f, Dark => #d1573124
    static var common_orange3_color: CGColor {
        getDynamicColor("common_orange3_color", ["#fd74431f", "#d1573124"], UIColor(rgba: "#fd74431f").cgColor)
    }

    /// Light => #ff9347ff, Dark => #c0632bff
    static var common_orange4_color: CGColor {
        getDynamicColor("common_orange4_color", ["#ff9347ff", "#c0632bff"], UIColor(rgba: "#ff9347ff").cgColor)
    }

    /// Light => #f14237ff, Dark => #bd3936ff
    static var common_red1_color: CGColor {
        getDynamicColor("common_red1_color", ["#f14237ff", "#bd3936ff"], UIColor(rgba: "#f14237ff").cgColor)
    }

    /// Light => #feecedff, Dark => #ff505a1f
    static var common_red2_color: CGColor {
        getDynamicColor("common_red2_color", ["#feecedff", "#ff505a1f"], UIColor(rgba: "#feecedff").cgColor)
    }

    /// Light => #7f8691ff, Dark => #8f99a8ff
    static var common_Bluishgrey1_color: CGColor {
        getDynamicColor("common_Bluishgrey1_color", ["#7f8691ff", "#8f99a8ff"], UIColor(rgba: "#7f8691ff").cgColor)
    }

    /// Light => #e8eef8ff, Dark => #e8eef824
    static var common_Bluishgrey2_color: CGColor {
        getDynamicColor("common_Bluishgrey2_color", ["#e8eef8ff", "#e8eef824"], UIColor(rgba: "#e8eef8ff").cgColor)
    }

    /// Light => #dee3e8ff, Dark => #1a2432ff
    static var common_Bluishgrey3_color: CGColor {
        getDynamicColor("common_Bluishgrey3_color", ["#dee3e8ff", "#1a2432ff"], UIColor(rgba: "#dee3e8ff").cgColor)
    }

    /// Light => #dfe1e6ff, Dark => #1d293aff
    static var common_Bluishgrey4_color: CGColor {
        getDynamicColor("common_Bluishgrey4_color", ["#dfe1e6ff", "#1d293aff"], UIColor(rgba: "#dfe1e6ff").cgColor)
    }

    /// Light => #b9bec5ff, Dark => #73757aff
    static var common_Bluishgrey5_color: CGColor {
        getDynamicColor("common_Bluishgrey5_color", ["#b9bec5ff", "#73757aff"], UIColor(rgba: "#b9bec5ff").cgColor)
    }

    /// Light => #3160a4ff, Dark => #527fb6ff
    static var common_blue1_color: CGColor {
        getDynamicColor("common_blue1_color", ["#3160a4ff", "#527fb6ff"], UIColor(rgba: "#3160a4ff").cgColor)
    }

    /// Light => #5494ffff, Dark => #70a0feff
    static var common_blue2_color: CGColor {
        getDynamicColor("common_blue2_color", ["#5494ffff", "#70a0feff"], UIColor(rgba: "#5494ffff").cgColor)
    }

    /// Light => #e6efffff, Dark => #5494ff33
    static var common_blue3_color: CGColor {
        getDynamicColor("common_blue3_color", ["#e6efffff", "#5494ff33"], UIColor(rgba: "#e6efffff").cgColor)
    }

    /// Light => #5e7dffff, Dark => #84a1ffff
    static var common_blue4_color: CGColor {
        getDynamicColor("common_blue4_color", ["#5e7dffff", "#84a1ffff"], UIColor(rgba: "#5e7dffff").cgColor)
    }

    /// Light => #6ca3ffff, Dark => #3f6cc9ff
    static var common_blue5_color: CGColor {
        getDynamicColor("common_blue5_color", ["#6ca3ffff", "#3f6cc9ff"], UIColor(rgba: "#6ca3ffff").cgColor)
    }

    /// Light => #2cbfa4ff, Dark => #58ccb3ff
    static var common_turquoise1_color: CGColor {
        getDynamicColor("common_turquoise1_color", ["#2cbfa4ff", "#58ccb3ff"], UIColor(rgba: "#2cbfa4ff").cgColor)
    }

    /// Light => #00d5b3ff, Dark => #0c9183ff
    static var common_turquoise2_color: CGColor {
        getDynamicColor("common_turquoise2_color", ["#00d5b3ff", "#0c9183ff"], UIColor(rgba: "#00d5b3ff").cgColor)
    }

    /// Light => #fffbeaff, Dark => #2d2819ff
    static var common_yellow1_color: CGColor {
        getDynamicColor("common_yellow1_color", ["#fffbeaff", "#2d2819ff"], UIColor(rgba: "#fffbeaff").cgColor)
    }

    /// Light => #61c4f2ff, Dark => #2476a7ff
    static var common_wathet1_color: CGColor {
        getDynamicColor("common_wathet1_color", ["#61c4f2ff", "#2476a7ff"], UIColor(rgba: "#61c4f2ff").cgColor)
    }

    /// Light => #66c862ff, Dark => #28822aff
    static var common_green1_color: CGColor {
        getDynamicColor("common_green1_color", ["#66c862ff", "#28822aff"], UIColor(rgba: "#66c862ff").cgColor)
    }

    /// Light => #f8bb06ff, Dark => #ae7c0bff
    static var common_yellow2_color: CGColor {
        getDynamicColor("common_yellow2_color", ["#f8bb06ff", "#ae7c0bff"], UIColor(rgba: "#f8bb06ff").cgColor)
    }

    /// Light => #f46dbeff, Dark => #b7398bff
    static var common_carmine1_color: CGColor {
        getDynamicColor("common_carmine1_color", ["#f46dbeff", "#b7398bff"], UIColor(rgba: "#f46dbeff").cgColor)
    }

    /// Light => #db7de9ff, Dark => #9538aaff
    static var common_violet1_color: CGColor {
        getDynamicColor("common_violet1_color", ["#db7de9ff", "#9538aaff"], UIColor(rgba: "#db7de9ff").cgColor)
    }

    /// Light => #af82f9ff, Dark => #7248c5ff
    static var common_purple1_color: CGColor {
        getDynamicColor("common_purple1_color", ["#af82f9ff", "#7248c5ff"], UIColor(rgba: "#af82f9ff").cgColor)
    }

    /// Light => #8391efff, Dark => #4651b9ff
    static var common_indigo1_color: CGColor {
        getDynamicColor("common_indigo1_color", ["#8391efff", "#4651b9ff"], UIColor(rgba: "#8391efff").cgColor)
    }

    /// Light => #f18b001a, Dark => #f18b001f
    static var common_yellow3_color: CGColor {
        getDynamicColor("common_yellow3_color", ["#f18b001a", "#f18b001f"], UIColor(rgba: "#f18b001a").cgColor)
    }

    /// Light => #f18b00ff, Dark => #d27900ff
    static var common_yellow4_color: CGColor {
        getDynamicColor("common_yellow4_color", ["#f18b00ff", "#d27900ff"], UIColor(rgba: "#f18b00ff").cgColor)
    }

    /// Light => #ffffffff, Dark => #0e0e0efc
    static var common_bg12_color: CGColor {
        getDynamicColor("common_bg12_color", ["#ffffffff", "#0e0e0efc"], UIColor(rgba: "#ffffffff").cgColor)
    }

    /// Light => #ffffff4d, Dark => #ffffff4d
    static var common_bg13_color: CGColor {
        getDynamicColor("common_bg13_color", ["#ffffff4d", "#ffffff4d"], UIColor(rgba: "#ffffff4d").cgColor)
    }

    /// Light => #fd744314, Dark => #d1573114
    static var common_bg15_color: CGColor {
        getDynamicColor("common_bg15_color", ["#fd744314", "#d1573114"], UIColor(rgba: "#fd744314").cgColor)
    }

    /// Light => #e6e6e7ff, Dark => #535353ff
    static var common_bg18_color: CGColor {
        getDynamicColor("common_bg18_color", ["#e6e6e7ff", "#535353ff"], UIColor(rgba: "#e6e6e7ff").cgColor)
    }

    /// Light => #cdcdcdff, Dark => #393939ff
    static var common_bg19_color: CGColor {
        getDynamicColor("common_bg19_color", ["#cdcdcdff", "#393939ff"], UIColor(rgba: "#cdcdcdff").cgColor)
    }

    /// Light => #c54e00ff, Dark => #c54e00ff
    static var common_orange5_color: CGColor {
        getDynamicColor("common_orange5_color", ["#c54e00ff", "#c54e00ff"], UIColor(rgba: "#c54e00ff").cgColor)
    }

    /// Light => #ff8628ff, Dark => #cc6725ff
    static var common_orange6_color: CGColor {
        getDynamicColor("common_orange6_color", ["#ff8628ff", "#cc6725ff"], UIColor(rgba: "#ff8628ff").cgColor)
    }

    /// Light => #fff4e9ff, Dark => #4f2a0cff
    static var common_orange7_color: CGColor {
        getDynamicColor("common_orange7_color", ["#fff4e9ff", "#4f2a0cff"], UIColor(rgba: "#fff4e9ff").cgColor)
    }

    /// Light => #c54e00ff, Dark => #e7a87aff
    static var common_orange8_color: CGColor {
        getDynamicColor("common_orange8_color", ["#c54e00ff", "#e7a87aff"], UIColor(rgba: "#c54e00ff").cgColor)
    }

    /// Light => #ff6f50ff, Dark => #c73514ff
    static var common_red_checkbox_color: CGColor {
        getDynamicColor("common_red_checkbox_color", ["#ff6f50ff", "#c73514ff"], UIColor(rgba: "#ff6f50ff").cgColor)
    }

    /// Light => #ffa500ff, Dark => #d58a00ff
    static var common_yellow_checkbox_color: CGColor {
        getDynamicColor("common_yellow_checkbox_color", ["#ffa500ff", "#d58a00ff"], UIColor(rgba: "#ffa500ff").cgColor)
    }

    /// Light => #fa9781ff, Dark => #8a4a3cff
    static var common_orange9_color: CGColor {
        getDynamicColor("common_orange9_color", ["#fa9781ff", "#8a4a3cff"], UIColor(rgba: "#fa9781ff").cgColor)
    }

    /// Light => #facd59ff, Dark => #997e38ff
    static var common_yellow_prior_color: CGColor {
        getDynamicColor("common_yellow_prior_color", ["#facd59ff", "#997e38ff"], UIColor(rgba: "#facd59ff").cgColor)
    }

    /// Light => #f85e5eff, Dark => #9c2a2aff
    static var common_red3_color: CGColor {
        getDynamicColor("common_red3_color", ["#f85e5eff", "#9c2a2aff"], UIColor(rgba: "#f85e5eff").cgColor)
    }

    /// Light => #fef2f2ff, Dark => #512222ff
    static var common_red4_color: CGColor {
        getDynamicColor("common_red4_color", ["#fef2f2ff", "#512222ff"], UIColor(rgba: "#fef2f2ff").cgColor)
    }

    /// Light => #d42f2fff, Dark => #f89393ff
    static var common_red5_color: CGColor {
        getDynamicColor("common_red5_color", ["#d42f2fff", "#f89393ff"], UIColor(rgba: "#d42f2fff").cgColor)
    }

    /// Light => #d42f2fff, Dark => #d42f2fff
    static var common_red6_color: CGColor {
        getDynamicColor("common_red6_color", ["#d42f2fff", "#d42f2fff"], UIColor(rgba: "#d42f2fff").cgColor)
    }

    /// Light => #ff563bcc, Dark => #d04a34ff
    static var common_red7_color: CGColor {
        getDynamicColor("common_red7_color", ["#ff563bcc", "#d04a34ff"], UIColor(rgba: "#ff563bcc").cgColor)
    }

    /// Light => #9dadc5ff, Dark => #527fb633
    static var commom_Bluishgrey6_color: CGColor {
        getDynamicColor("commom_Bluishgrey6_color", ["#9dadc5ff", "#527fb633"], UIColor(rgba: "#9dadc5ff").cgColor)
    }

    /// Light => #eff0f4ff, Dark => #eff0f41a
    static var common_Bluishgrey8_color: CGColor {
        getDynamicColor("common_Bluishgrey8_color", ["#eff0f4ff", "#eff0f41a"], UIColor(rgba: "#eff0f4ff").cgColor)
    }

    /// Light => #5494ffff, Dark => #3669bfff
    static var common_blue6_color: CGColor {
        getDynamicColor("common_blue6_color", ["#5494ffff", "#3669bfff"], UIColor(rgba: "#5494ffff").cgColor)
    }

    /// Light => #f1f8ffff, Dark => #142037ff
    static var common_blue7_color: CGColor {
        getDynamicColor("common_blue7_color", ["#f1f8ffff", "#142037ff"], UIColor(rgba: "#f1f8ffff").cgColor)
    }

    /// Light => #2c5da7ff, Dark => #99bbffff
    static var common_blue8_color: CGColor {
        getDynamicColor("common_blue8_color", ["#2c5da7ff", "#99bbffff"], UIColor(rgba: "#2c5da7ff").cgColor)
    }

    /// Light => #2c5da7ff, Dark => #2c5da7ff
    static var common_blue9_color: CGColor {
        getDynamicColor("common_blue9_color", ["#2c5da7ff", "#2c5da7ff"], UIColor(rgba: "#2c5da7ff").cgColor)
    }

    /// Light => #3a97ffff, Dark => #3365b8ff
    static var common_blue10_checkbox_color: CGColor {
        getDynamicColor("common_blue10_checkbox_color", ["#3a97ffff", "#3365b8ff"], UIColor(rgba: "#3a97ffff").cgColor)
    }

    /// Light => #bedaf9ff, Dark => #667a90ff
    static var common_blue11_color: CGColor {
        getDynamicColor("common_blue11_color", ["#bedaf9ff", "#667a90ff"], UIColor(rgba: "#bedaf9ff").cgColor)
    }

    /// Light => #00bea4ff, Dark => #00a08aff
    static var common_turquoise3_color: CGColor {
        getDynamicColor("common_turquoise3_color", ["#00bea4ff", "#00a08aff"], UIColor(rgba: "#00bea4ff").cgColor)
    }

    /// Light => #eafbf7ff, Dark => #112d29ff
    static var common_turquoise4_color: CGColor {
        getDynamicColor("common_turquoise4_color", ["#eafbf7ff", "#112d29ff"], UIColor(rgba: "#eafbf7ff").cgColor)
    }

    /// Light => #00836eff, Dark => #77dbcdff
    static var common_turquoise5_color: CGColor {
        getDynamicColor("common_turquoise5_color", ["#00836eff", "#77dbcdff"], UIColor(rgba: "#00836eff").cgColor)
    }

    /// Light => #00836eff, Dark => #00836eff
    static var common_turquoise6_color: CGColor {
        getDynamicColor("common_turquoise6_color", ["#00836eff", "#00836eff"], UIColor(rgba: "#00836eff").cgColor)
    }

    /// Light => #7f90a9ff, Dark => #4b5e79ff
    static var common_grey1_color: CGColor {
        getDynamicColor("common_grey1_color", ["#7f90a9ff", "#4b5e79ff"], UIColor(rgba: "#7f90a9ff").cgColor)
    }

    /// Light => #f1f4f7ff, Dark => #1b2a35ff
    static var common_grey2_color: CGColor {
        getDynamicColor("common_grey2_color", ["#f1f4f7ff", "#1b2a35ff"], UIColor(rgba: "#f1f4f7ff").cgColor)
    }

    /// Light => #37668aff, Dark => #bad6eaff
    static var common_grey3_color: CGColor {
        getDynamicColor("common_grey3_color", ["#37668aff", "#bad6eaff"], UIColor(rgba: "#37668aff").cgColor)
    }

    /// Light => #37668aff, Dark => #37668aff
    static var common_grey4_color: CGColor {
        getDynamicColor("common_grey4_color", ["#37668aff", "#37668aff"], UIColor(rgba: "#37668aff").cgColor)
    }

    /// Light => #06aeeaff, Dark => #008abbff
    static var common_wathet2_color: CGColor {
        getDynamicColor("common_wathet2_color", ["#06aeeaff", "#008abbff"], UIColor(rgba: "#06aeeaff").cgColor)
    }

    /// Light => #eff9fcff, Dark => #16323aff
    static var common_wathet3_color: CGColor {
        getDynamicColor("common_wathet3_color", ["#eff9fcff", "#16323aff"], UIColor(rgba: "#eff9fcff").cgColor)
    }

    /// Light => #0072adff, Dark => #82d0e6ff
    static var common_wathet4_color: CGColor {
        getDynamicColor("common_wathet4_color", ["#0072adff", "#82d0e6ff"], UIColor(rgba: "#0072adff").cgColor)
    }

    /// Light => #0072adff, Dark => #0072adff
    static var common_wathet5_color: CGColor {
        getDynamicColor("common_wathet5_color", ["#0072adff", "#0072adff"], UIColor(rgba: "#0072adff").cgColor)
    }

    /// Light => #48b855ff, Dark => #3c9446ff
    static var common_green2_color: CGColor {
        getDynamicColor("common_green2_color", ["#48b855ff", "#3c9446ff"], UIColor(rgba: "#48b855ff").cgColor)
    }

    /// Light => #ecfaebff, Dark => #173914ff
    static var common_green3_color: CGColor {
        getDynamicColor("common_green3_color", ["#ecfaebff", "#173914ff"], UIColor(rgba: "#ecfaebff").cgColor)
    }

    /// Light => #1f8412ff, Dark => #7dcb79ff
    static var common_green4_color: CGColor {
        getDynamicColor("common_green4_color", ["#1f8412ff", "#7dcb79ff"], UIColor(rgba: "#1f8412ff").cgColor)
    }

    /// Light => #1f8412ff, Dark => #1f8412ff
    static var common_green5_color: CGColor {
        getDynamicColor("common_green5_color", ["#1f8412ff", "#1f8412ff"], UIColor(rgba: "#1f8412ff").cgColor)
    }

    /// Light => #eead07ff, Dark => #b88400ff
    static var common_yellow5_color: CGColor {
        getDynamicColor("common_yellow5_color", ["#eead07ff", "#b88400ff"], UIColor(rgba: "#eead07ff").cgColor)
    }

    /// Light => #fcf7e3ff, Dark => #463714ff
    static var common_yellow6_color: CGColor {
        getDynamicColor("common_yellow6_color", ["#fcf7e3ff", "#463714ff"], UIColor(rgba: "#fcf7e3ff").cgColor)
    }

    /// Light => #a06800ff, Dark => #d4b076ff
    static var common_yellow7_color: CGColor {
        getDynamicColor("common_yellow7_color", ["#a06800ff", "#d4b076ff"], UIColor(rgba: "#a06800ff").cgColor)
    }

    /// Light => #a06800ff, Dark => #a06800ff
    static var common_yellow8_color: CGColor {
        getDynamicColor("common_yellow8_color", ["#a06800ff", "#a06800ff"], UIColor(rgba: "#a06800ff").cgColor)
    }

    /// Light => #ee5694ff, Dark => #b63167ff
    static var common_carmine2_color: CGColor {
        getDynamicColor("common_carmine2_color", ["#ee5694ff", "#b63167ff"], UIColor(rgba: "#ee5694ff").cgColor)
    }

    /// Light => #fef2f9ff, Dark => #54223cff
    static var common_carmine3_color: CGColor {
        getDynamicColor("common_carmine3_color", ["#fef2f9ff", "#54223cff"], UIColor(rgba: "#fef2f9ff").cgColor)
    }

    /// Light => #a21e67ff, Dark => #ec82baff
    static var common_carmine4_color: CGColor {
        getDynamicColor("common_carmine4_color", ["#a21e67ff", "#ec82baff"], UIColor(rgba: "#a21e67ff").cgColor)
    }

    /// Light => #a21e67ff, Dark => #a21e67ff
    static var common_carmine5_color: CGColor {
        getDynamicColor("common_carmine5_color", ["#a21e67ff", "#a21e67ff"], UIColor(rgba: "#a21e67ff").cgColor)
    }

    /// Light => #cc5fd3ff, Dark => #892b8fff
    static var common_violet2_color: CGColor {
        getDynamicColor("common_violet2_color", ["#cc5fd3ff", "#892b8fff"], UIColor(rgba: "#cc5fd3ff").cgColor)
    }

    /// Light => #fbf2fbff, Dark => #461b46ff
    static var common_violet3_color: CGColor {
        getDynamicColor("common_violet3_color", ["#fbf2fbff", "#461b46ff"], UIColor(rgba: "#fbf2fbff").cgColor)
    }

    /// Light => #922592ff, Dark => #ea9aeaff
    static var common_violet4_color: CGColor {
        getDynamicColor("common_violet4_color", ["#922592ff", "#ea9aeaff"], UIColor(rgba: "#922592ff").cgColor)
    }

    /// Light => #922592ff, Dark => #922592ff
    static var common_violet5_color: CGColor {
        getDynamicColor("common_violet5_color", ["#922592ff", "#922592ff"], UIColor(rgba: "#922592ff").cgColor)
    }

    /// Light => #9572e8ff, Dark => #6540a8ff
    static var common_purple2_color: CGColor {
        getDynamicColor("common_purple2_color", ["#9572e8ff", "#6540a8ff"], UIColor(rgba: "#9572e8ff").cgColor)
    }

    /// Light => #f8f4ffff, Dark => #25153eff
    static var common_purple3_color: CGColor {
        getDynamicColor("common_purple3_color", ["#f8f4ffff", "#25153eff"], UIColor(rgba: "#f8f4ffff").cgColor)
    }

    /// Light => #6638b4ff, Dark => #ba90ffff
    static var common_purple4_color: CGColor {
        getDynamicColor("common_purple4_color", ["#6638b4ff", "#ba90ffff"], UIColor(rgba: "#6638b4ff").cgColor)
    }

    /// Light => #6638b4ff, Dark => #6638b4ff
    static var common_purple5_color: CGColor {
        getDynamicColor("common_purple5_color", ["#6638b4ff", "#6638b4ff"], UIColor(rgba: "#6638b4ff").cgColor)
    }

    /// Light => #7881e6ff, Dark => #474fadff
    static var common_indigo2_color: CGColor {
        getDynamicColor("common_indigo2_color", ["#7881e6ff", "#474fadff"], UIColor(rgba: "#7881e6ff").cgColor)
    }

    /// Light => #f4f5fdff, Dark => #1d2042ff
    static var common_indigo3_color: CGColor {
        getDynamicColor("common_indigo3_color", ["#f4f5fdff", "#1d2042ff"], UIColor(rgba: "#f4f5fdff").cgColor)
    }

    /// Light => #424ab4ff, Dark => #a6adfcff
    static var common_indigo4_color: CGColor {
        getDynamicColor("common_indigo4_color", ["#424ab4ff", "#a6adfcff"], UIColor(rgba: "#424ab4ff").cgColor)
    }

    /// Light => #424ab4ff, Dark => #424ab4ff
    static var common_indigo5_color: CGColor {
        getDynamicColor("common_indigo5_color", ["#424ab4ff", "#424ab4ff"], UIColor(rgba: "#424ab4ff").cgColor)
    }

    /// Light => #aa7d65ff, Dark => #7e5744ff
    static var common_brown1_color: CGColor {
        getDynamicColor("common_brown1_color", ["#aa7d65ff", "#7e5744ff"], UIColor(rgba: "#aa7d65ff").cgColor)
    }

    /// Light => #f8f4f2ff, Dark => #2c1d15ff
    static var common_brown2_color: CGColor {
        getDynamicColor("common_brown2_color", ["#f8f4f2ff", "#2c1d15ff"], UIColor(rgba: "#f8f4f2ff").cgColor)
    }

    /// Light => #8e4f2eff, Dark => #ddc2b5ff
    static var common_brown3_color: CGColor {
        getDynamicColor("common_brown3_color", ["#8e4f2eff", "#ddc2b5ff"], UIColor(rgba: "#8e4f2eff").cgColor)
    }

    /// Light => #8e4f2eff, Dark => #8e4f2eff
    static var common_brown4_color: CGColor {
        getDynamicColor("common_brown4_color", ["#8e4f2eff", "#8e4f2eff"], UIColor(rgba: "#8e4f2eff").cgColor)
    }

    /// Light => #f5f6faff, Dark => #0e0e0eff
    static var common_bg21_color: CGColor {
        getDynamicColor("common_bg21_color", ["#f5f6faff", "#0e0e0eff"], UIColor(rgba: "#f5f6faff").cgColor)
    }

    /// Light => #b9b9b9ff, Dark => #3a3a3aff
    static var common_bg22_color: CGColor {
        getDynamicColor("common_bg22_color", ["#b9b9b9ff", "#3a3a3aff"], UIColor(rgba: "#b9b9b9ff").cgColor)
    }

    /// Light => #ffffffe6, Dark => #1a1a1ae6
    static var common_bg24_color: CGColor {
        getDynamicColor("common_bg24_color", ["#ffffffe6", "#1a1a1ae6"], UIColor(rgba: "#ffffffe6").cgColor)
    }

    /// Light => #f1f1f1ff, Dark => #3e3e3efc
    static var common_bg26_color: CGColor {
        getDynamicColor("common_bg26_color", ["#f1f1f1ff", "#3e3e3efc"], UIColor(rgba: "#f1f1f1ff").cgColor)
    }

    /// Light => #ffffffff, Dark => #1a1a1aff
    static var common_bg_mask3_color: CGColor {
        getDynamicColor("common_bg_mask3_color", ["#ffffffff", "#1a1a1aff"], UIColor(rgba: "#ffffffff").cgColor)
    }

    /// Light => #ffffff66, Dark => #1a1a1a66
    static var common_bg_mask4_color: CGColor {
        getDynamicColor("common_bg_mask4_color", ["#ffffff66", "#1a1a1a66"], UIColor(rgba: "#ffffff66").cgColor)
    }

    /// Light => #fd7d48ff, Dark => #fd7d48ff
    static var common_orange10_color: CGColor {
        getDynamicColor("common_orange10_color", ["#fd7d48ff", "#fd7d48ff"], UIColor(rgba: "#fd7d48ff").cgColor)
    }

    /// Light => #eff5f9ff, Dark => #3a97ff1a
    static var common_Bluishgrey9_color: CGColor {
        getDynamicColor("common_Bluishgrey9_color", ["#eff5f9ff", "#3a97ff1a"], UIColor(rgba: "#eff5f9ff").cgColor)
    }

    /// Light => #3e7efbff, Dark => #3e7efbff
    static var common_blue12_color: CGColor {
        getDynamicColor("common_blue12_color", ["#3e7efbff", "#3e7efbff"], UIColor(rgba: "#3e7efbff").cgColor)
    }

    /// Light => #7a8aa9ff, Dark => #7a8aa9ff
    static var common_grey10_color: CGColor {
        getDynamicColor("common_grey10_color", ["#7a8aa9ff", "#7a8aa9ff"], UIColor(rgba: "#7a8aa9ff").cgColor)
    }

    /// Light => #08c2a9ff, Dark => #08c2a9ff
    static var common_turquoise9_color: CGColor {
        getDynamicColor("common_turquoise9_color", ["#08c2a9ff", "#08c2a9ff"], UIColor(rgba: "#08c2a9ff").cgColor)
    }

    /// Light => #39b44fff, Dark => #39b44fff
    static var common_green6_color: CGColor {
        getDynamicColor("common_green6_color", ["#39b44fff", "#39b44fff"], UIColor(rgba: "#39b44fff").cgColor)
    }

    /// Light => #fdb706ff, Dark => #fdb706ff
    static var common_yellow9_color: CGColor {
        getDynamicColor("common_yellow9_color", ["#fdb706ff", "#fdb706ff"], UIColor(rgba: "#fdb706ff").cgColor)
    }

    /// Light => #f26199ff, Dark => #f26199ff
    static var common_carmine6_color: CGColor {
        getDynamicColor("common_carmine6_color", ["#f26199ff", "#f26199ff"], UIColor(rgba: "#f26199ff").cgColor)
    }

    /// Light => #8f68d5ff, Dark => #8f68d5ff
    static var common_purple6_color: CGColor {
        getDynamicColor("common_purple6_color", ["#8f68d5ff", "#8f68d5ff"], UIColor(rgba: "#8f68d5ff").cgColor)
    }

    /// Light => #ffffffcc, Dark => #ffffff0a
    static var common_bg14_color: CGColor {
        getDynamicColor("common_bg14_color", ["#ffffffcc", "#ffffff0a"], UIColor(rgba: "#ffffffcc").cgColor)
    }

    /// Light => #fbfbfbff, Dark => #1d1d1dff
    static var common_bg16_color: CGColor {
        getDynamicColor("common_bg16_color", ["#fbfbfbff", "#1d1d1dff"], UIColor(rgba: "#fbfbfbff").cgColor)
    }

    /// Light => #fbfbfbff, Dark => #141414ff
    static var common_bg17_color: CGColor {
        getDynamicColor("common_bg17_color", ["#fbfbfbff", "#141414ff"], UIColor(rgba: "#fbfbfbff").cgColor)
    }

    /// Light => #ffffffff, Dark => #2a2a2aff
    static var common_bg20_color: CGColor {
        getDynamicColor("common_bg20_color", ["#ffffffff", "#2a2a2aff"], UIColor(rgba: "#ffffffff").cgColor)
    }

    /// Light => #1f1f2533, Dark => #00000033
    static var common_shadow2_color: CGColor {
        getDynamicColor("common_shadow2_color", ["#1f1f2533", "#00000033"], UIColor(rgba: "#1f1f2533").cgColor)
    }

    /// Light => #ffffff1f, Dark => #ffffff1f
    static var common_line5_color: CGColor {
        getDynamicColor("common_line5_color", ["#ffffff1f", "#ffffff1f"], UIColor(rgba: "#ffffff1f").cgColor)
    }

    /// Light => #111111ff, Dark => #fffffff2
    static var common_level7_color: CGColor {
        getDynamicColor("common_level7_color", ["#111111ff", "#fffffff2"], UIColor(rgba: "#111111ff").cgColor)
    }

    /// Light => #ff5833ff, Dark => #d53613ff
    static var common_level_alert_color: CGColor {
        getDynamicColor("common_level_alert_color", ["#ff5833ff", "#d53613ff"], UIColor(rgba: "#ff5833ff").cgColor)
    }

    /// Light => #a4a4a4ff, Dark => #ffffff73
    static var common_level8_color: CGColor {
        getDynamicColor("common_level8_color", ["#a4a4a4ff", "#ffffff73"], UIColor(rgba: "#a4a4a4ff").cgColor)
    }

    /// Light => #505050ff, Dark => #ffffff99
    static var common_level9_color: CGColor {
        getDynamicColor("common_level9_color", ["#505050ff", "#ffffff99"], UIColor(rgba: "#505050ff").cgColor)
    }

    /// Light => #b2b2b2ff, Dark => #ffffff59
    static var common_level10_color: CGColor {
        getDynamicColor("common_level10_color", ["#b2b2b2ff", "#ffffff59"], UIColor(rgba: "#b2b2b2ff").cgColor)
    }

    /// Light => #000000ff, Dark => #ffffffff
    static var common_level11_color: CGColor {
        getDynamicColor("common_level11_color", ["#000000ff", "#ffffffff"], UIColor(rgba: "#000000ff").cgColor)
    }

    /// Light => #fd7443ff, Dark => #d15731ff
    static var common_level12_color: CGColor {
        getDynamicColor("common_level12_color", ["#fd7443ff", "#d15731ff"], UIColor(rgba: "#fd7443ff").cgColor)
    }

    /// Light => #fd762cff, Dark => #d15731ff
    static var common_level13_color: CGColor {
        getDynamicColor("common_level13_color", ["#fd762cff", "#d15731ff"], UIColor(rgba: "#fd762cff").cgColor)
    }

    /// Light => #252629ff, Dark => #fffffffc
    static var common_level14_color: CGColor {
        getDynamicColor("common_level14_color", ["#252629ff", "#fffffffc"], UIColor(rgba: "#252629ff").cgColor)
    }

    /// Light => #fd7443ff, Dark => #d15731ff
    static var common_line6_color: CGColor {
        getDynamicColor("common_line6_color", ["#fd7443ff", "#d15731ff"], UIColor(rgba: "#fd7443ff").cgColor)
    }

    /// Light => #dadadaff, Dark => #ffffff26
    static var common_line7_color: CGColor {
        getDynamicColor("common_line7_color", ["#dadadaff", "#ffffff26"], UIColor(rgba: "#dadadaff").cgColor)
    }

    /// Light => #dededeff, Dark => #ffffff33
    static var common_line8_color: CGColor {
        getDynamicColor("common_line8_color", ["#dededeff", "#ffffff33"], UIColor(rgba: "#dededeff").cgColor)
    }

    /// Light => #eaeaeaff, Dark => #ffffff26
    static var common_line9_color: CGColor {
        getDynamicColor("common_line9_color", ["#eaeaeaff", "#ffffff26"], UIColor(rgba: "#eaeaeaff").cgColor)
    }

    /// Light => #c0c0c0ff, Dark => #ffffff33
    static var common_line10_color: CGColor {
        getDynamicColor("common_line10_color", ["#c0c0c0ff", "#ffffff33"], UIColor(rgba: "#c0c0c0ff").cgColor)
    }

    /// Light => #f3f3f3ff, Dark => #2a2a2aff
    static var common_line11_color: CGColor {
        getDynamicColor("common_line11_color", ["#f3f3f3ff", "#2a2a2aff"], UIColor(rgba: "#f3f3f3ff").cgColor)
    }

    /// Light => #f2f2f7ff, Dark => #1a1a1aff
    static var common_bg23_color: CGColor {
        getDynamicColor("common_bg23_color", ["#f2f2f7ff", "#1a1a1aff"], UIColor(rgba: "#f2f2f7ff").cgColor)
    }

    /// Light => #222525ff, Dark => #d15731ff
    static var common_bg25_color: CGColor {
        getDynamicColor("common_bg25_color", ["#222525ff", "#d15731ff"], UIColor(rgba: "#222525ff").cgColor)
    }

    /// Light => #f34c42ff, Dark => #bd3936ff
    static var common_red8_color: CGColor {
        getDynamicColor("common_red8_color", ["#f34c42ff", "#bd3936ff"], UIColor(rgba: "#f34c42ff").cgColor)
    }

    /// Light => #ff5133ff, Dark => #e54320ff
    static var common_red9_color: CGColor {
        getDynamicColor("common_red9_color", ["#ff5133ff", "#e54320ff"], UIColor(rgba: "#ff5133ff").cgColor)
    }

    /// Light => #ff4133ff, Dark => #d33632ff
    static var common_red10_color: CGColor {
        getDynamicColor("common_red10_color", ["#ff4133ff", "#d33632ff"], UIColor(rgba: "#ff4133ff").cgColor)
    }

    /// Light => #fef0f1ff, Dark => #d157311a
    static var common_red11_color: CGColor {
        getDynamicColor("common_red11_color", ["#fef0f1ff", "#d157311a"], UIColor(rgba: "#fef0f1ff").cgColor)
    }

    /// Light => #ff563bff, Dark => #d84128ff
    static var common_red12_color: CGColor {
        getDynamicColor("common_red12_color", ["#ff563bff", "#d84128ff"], UIColor(rgba: "#ff563bff").cgColor)
    }

    /// Light => #a8acb5ff, Dark => #444850ff
    static var common_Bluishgrey7_color: CGColor {
        getDynamicColor("common_Bluishgrey7_color", ["#a8acb5ff", "#444850ff"], UIColor(rgba: "#a8acb5ff").cgColor)
    }

    /// Light => #2cbfa4ff, Dark => #18a58bff
    static var common_turquoise7_color: CGColor {
        getDynamicColor("common_turquoise7_color", ["#2cbfa4ff", "#18a58bff"], UIColor(rgba: "#2cbfa4ff").cgColor)
    }

    /// Light => #2ecda4ff, Dark => #18be9fff
    static var common_turquoise8_color: CGColor {
        getDynamicColor("common_turquoise8_color", ["#2ecda4ff", "#18be9fff"], UIColor(rgba: "#2ecda4ff").cgColor)
    }

    /// Light => #71757dff, Dark => #b9babcff
    static var common_grey5_color: CGColor {
        getDynamicColor("common_grey5_color", ["#71757dff", "#b9babcff"], UIColor(rgba: "#71757dff").cgColor)
    }

    /// Light => #bbbbbbff, Dark => #ffffff66
    static var common_grey6_color: CGColor {
        getDynamicColor("common_grey6_color", ["#bbbbbbff", "#ffffff66"], UIColor(rgba: "#bbbbbbff").cgColor)
    }

    /// Light => #616061ff, Dark => #ffffff73
    static var common_grey7_color: CGColor {
        getDynamicColor("common_grey7_color", ["#616061ff", "#ffffff73"], UIColor(rgba: "#616061ff").cgColor)
    }

    /// Light => #c2c2c2ff, Dark => #ffffff40
    static var connom_grey8_color: CGColor {
        getDynamicColor("connom_grey8_color", ["#c2c2c2ff", "#ffffff40"], UIColor(rgba: "#c2c2c2ff").cgColor)
    }

    /// Light => #c0c0c0ff, Dark => #ffffff33
    static var common_grey9_color: CGColor {
        getDynamicColor("common_grey9_color", ["#c0c0c0ff", "#ffffff33"], UIColor(rgba: "#c0c0c0ff").cgColor)
    }

    /// Light => #9699a5ff, Dark => #ffffff80
    static var common_level15_color: CGColor {
        getDynamicColor("common_level15_color", ["#9699a5ff", "#ffffff80"], UIColor(rgba: "#9699a5ff").cgColor)
    }

    /// Light => #f7f7f7ff, Dark => #262626fc
    static var common_bg_touch3_color: CGColor {
        getDynamicColor("common_bg_touch3_color", ["#f7f7f7ff", "#262626fc"], UIColor(rgba: "#f7f7f7ff").cgColor)
    }

    /// Light => #e0e0e0ff, Dark => #ffffff1f
    static var common_line12_color: CGColor {
        getDynamicColor("common_line12_color", ["#e0e0e0ff", "#ffffff1f"], UIColor(rgba: "#e0e0e0ff").cgColor)
    }

    /// Light => #eeeeeeff, Dark => #1a1a1aff
    static var common_bg27_color: CGColor {
        getDynamicColor("common_bg27_color", ["#eeeeeeff", "#1a1a1aff"], UIColor(rgba: "#eeeeeeff").cgColor)
    }

    /// Light => #ffffffff, Dark => #ffffff99
    static var common_level16_color: CGColor {
        getDynamicColor("common_level16_color", ["#ffffffff", "#ffffff99"], UIColor(rgba: "#ffffffff").cgColor)
    }

    /// Light => #bbbbbbff, Dark => #ffffff66
    static var common_icon1_color: CGColor {
        getDynamicColor("common_icon1_color", ["#bbbbbbff", "#ffffff66"], UIColor(rgba: "#bbbbbbff").cgColor)
    }

    /// Light => #282a30ff, Dark => #ffffffe6
    static var common_icon2_color: CGColor {
        getDynamicColor("common_icon2_color", ["#282a30ff", "#ffffffe6"], UIColor(rgba: "#282a30ff").cgColor)
    }

    /// Light => #aeaeaeff, Dark => #ffffff6b
    static var common_level17_color: CGColor {
        getDynamicColor("common_level17_color", ["#aeaeaeff", "#ffffff6b"], UIColor(rgba: "#aeaeaeff").cgColor)
    }

    /// Light => #ffffffff, Dark => #ffffffff
    static var common_icon3_color: CGColor {
        getDynamicColor("common_icon3_color", ["#ffffffff", "#ffffffff"], UIColor(rgba: "#ffffffff").cgColor)
    }

    /// Light => #5f6972ff, Dark => #ffffffb3
    static var common_icon4_color: CGColor {
        getDynamicColor("common_icon4_color", ["#5f6972ff", "#ffffffb3"], UIColor(rgba: "#5f6972ff").cgColor)
    }

    /// Light => #909090ff, Dark => #ffffff80
    static var common_icon5_color: CGColor {
        getDynamicColor("common_icon5_color", ["#909090ff", "#ffffff80"], UIColor(rgba: "#909090ff").cgColor)
    }

    /// Light => #888888ff, Dark => #ffffff73
    static var common_icon6_color: CGColor {
        getDynamicColor("common_icon6_color", ["#888888ff", "#ffffff73"], UIColor(rgba: "#888888ff").cgColor)
    }

    /// Light => #b3b7bdff, Dark => #ffffff80
    static var common_icon7_color: CGColor {
        getDynamicColor("common_icon7_color", ["#b3b7bdff", "#ffffff80"], UIColor(rgba: "#b3b7bdff").cgColor)
    }

    /// Light => #bbbbbbff, Dark => #ffffff66
    static var common_level18_color: CGColor {
        getDynamicColor("common_level18_color", ["#bbbbbbff", "#ffffff66"], UIColor(rgba: "#bbbbbbff").cgColor)
    }

    /// Light => #666666ff, Dark => #ffffffe6
    static var common_level19_color: CGColor {
        getDynamicColor("common_level19_color", ["#666666ff", "#ffffffe6"], UIColor(rgba: "#666666ff").cgColor)
    }

    /// Light => #bbbbbbff, Dark => #ffffff80
    static var common_level20_color: CGColor {
        getDynamicColor("common_level20_color", ["#bbbbbbff", "#ffffff80"], UIColor(rgba: "#bbbbbbff").cgColor)
    }

    /// Light => #e6e6e6ff, Dark => #ffffff33
    static var common_line13_color: CGColor {
        getDynamicColor("common_line13_color", ["#e6e6e6ff", "#ffffff33"], UIColor(rgba: "#e6e6e6ff").cgColor)
    }

    /// Light => #fbfbfbff, Dark => #ffffffcc
    static var common_level21_color: CGColor {
        getDynamicColor("common_level21_color", ["#fbfbfbff", "#ffffffcc"], UIColor(rgba: "#fbfbfbff").cgColor)
    }

    /// Light => #ffffffcc, Dark => #ffffffa8
    static var common_level22_color: CGColor {
        getDynamicColor("common_level22_color", ["#ffffffcc", "#ffffffa8"], UIColor(rgba: "#ffffffcc").cgColor)
    }

    /// Light => #ddddddff, Dark => #ffffff40
    static var common_bg28_color: CGColor {
        getDynamicColor("common_bg28_color", ["#ddddddff", "#ffffff40"], UIColor(rgba: "#ddddddff").cgColor)
    }

    /// Light => #ee444cff, Dark => #d75548ff
    static var common_red13_color: CGColor {
        getDynamicColor("common_red13_color", ["#ee444cff", "#d75548ff"], UIColor(rgba: "#ee444cff").cgColor)
    }

    /// Light => #a6721c99, Dark => #d09e39cc
    static var common_yellow10_color: CGColor {
        getDynamicColor("common_yellow10_color", ["#a6721c99", "#d09e39cc"], UIColor(rgba: "#a6721c99").cgColor)
    }

    /// Light => #ffecccff, Dark => #f3d198ff
    static var common_yellow11_color: CGColor {
        getDynamicColor("common_yellow11_color", ["#ffecccff", "#f3d198ff"], UIColor(rgba: "#ffecccff").cgColor)
    }

    /// Light => #f7dcb1ff, Dark => #f7dcb1ff
    static var common_yellow12_color: CGColor {
        getDynamicColor("common_yellow12_color", ["#f7dcb1ff", "#f7dcb1ff"], UIColor(rgba: "#f7dcb1ff").cgColor)
    }

    /// Light => #f1cd9299, Dark => #66513099
    static var common_yellow13_color: CGColor {
        getDynamicColor("common_yellow13_color", ["#f1cd9299", "#66513099"], UIColor(rgba: "#f1cd9299").cgColor)
    }

    /// Light => #f58f93ff, Dark => #e18076ff
    static var common_red14_color: CGColor {
        getDynamicColor("common_red14_color", ["#f58f93ff", "#e18076ff"], UIColor(rgba: "#f58f93ff").cgColor)
    }

    /// Light => #fff5f2ff, Dark => #d1573129
    static var common_orange11_color: CGColor {
        getDynamicColor("common_orange11_color", ["#fff5f2ff", "#d1573129"], UIColor(rgba: "#fff5f2ff").cgColor)
    }

    /// Light => #fefefeff, Dark => #262626fa
    static var common_bg29_color: CGColor {
        getDynamicColor("common_bg29_color", ["#fefefeff", "#262626fa"], UIColor(rgba: "#fefefeff").cgColor)
    }

    /// Light => #f7f7faff, Dark => #262628ff
    static var common_bluishgrey10_color: CGColor {
        getDynamicColor("common_bluishgrey10_color", ["#f7f7faff", "#262628ff"], UIColor(rgba: "#f7f7faff").cgColor)
    }

    /// Light => #ffffffff, Dark => #202020ff
    static var common_bg30_color: CGColor {
        getDynamicColor("common_bg30_color", ["#ffffffff", "#202020ff"], UIColor(rgba: "#ffffffff").cgColor)
    }

    /// Light => #f7f7faff, Dark => #3c3c3eff
    static var common_bg31_color: CGColor {
        getDynamicColor("common_bg31_color", ["#f7f7faff", "#3c3c3eff"], UIColor(rgba: "#f7f7faff").cgColor)
    }

    /// Light => #333333ff, Dark => #ffffffcc
    static var common_level23_color: CGColor {
        getDynamicColor("common_level23_color", ["#333333ff", "#ffffffcc"], UIColor(rgba: "#333333ff").cgColor)
    }

    /// Light => #00a59fff, Dark => #00a59fff
    static var common_turquoise10_color: CGColor {
        getDynamicColor("common_turquoise10_color", ["#00a59fff", "#00a59fff"], UIColor(rgba: "#00a59fff").cgColor)
    }

    /// Light => #00a59f14, Dark => #00a59f1f
    static var common_turquoise11_color: CGColor {
        getDynamicColor("common_turquoise11_color", ["#00a59f14", "#00a59f1f"], UIColor(rgba: "#00a59f14").cgColor)
    }

    /// Light => #ff9520ff, Dark => #ff9520ff
    static var common_orange12_color: CGColor {
        getDynamicColor("common_orange12_color", ["#ff9520ff", "#ff9520ff"], UIColor(rgba: "#ff9520ff").cgColor)
    }

    /// Light => #ff952014, Dark => #ff95201f
    static var common_orange13_color: CGColor {
        getDynamicColor("common_orange13_color", ["#ff952014", "#ff95201f"], UIColor(rgba: "#ff952014").cgColor)
    }

    /// Light => #fd74430d, Dark => #d157310d
    static var common_orange14_color: CGColor {
        getDynamicColor("common_orange14_color", ["#fd74430d", "#d157310d"], UIColor(rgba: "#fd74430d").cgColor)
    }

    /// Light => #222525e6, Dark => #d15731e6
    static var common_orange15_color: CGColor {
        getDynamicColor("common_orange15_color", ["#222525e6", "#d15731e6"], UIColor(rgba: "#222525e6").cgColor)
    }

    /// Light => #5b5b5bff, Dark => #ffffffe6
    static var common_icon8_color: CGColor {
        getDynamicColor("common_icon8_color", ["#5b5b5bff", "#ffffffe6"], UIColor(rgba: "#5b5b5bff").cgColor)
    }

    /// Light => #86909cff, Dark => #ffffff80
    static var common_level24_color: CGColor {
        getDynamicColor("common_level24_color", ["#86909cff", "#ffffff80"], UIColor(rgba: "#86909cff").cgColor)
    }

    /// Light => #96989eff, Dark => #ffffff99
    static var common_bluishgrey11_color: CGColor {
        getDynamicColor("common_bluishgrey11_color", ["#96989eff", "#ffffff99"], UIColor(rgba: "#96989eff").cgColor)
    }

    /// Light => #fd744333, Dark => #d1573133
    static var common_orange16_color: CGColor {
        getDynamicColor("common_orange16_color", ["#fd744333", "#d1573133"], UIColor(rgba: "#fd744333").cgColor)
    }

    /// Light => #ffe7ddff, Dark => #441c0cff
    static var common_line14_color: CGColor {
        getDynamicColor("common_line14_color", ["#ffe7ddff", "#441c0cff"], UIColor(rgba: "#ffe7ddff").cgColor)
    }

    /// Light => #ffffff00, Dark => #00000000
    static var common_clear_color: CGColor {
        getDynamicColor("common_clear_color", ["#ffffff00", "#00000000"], UIColor(rgba: "#ffffff00").cgColor)
    }

    /// Light => #bbbabbff, Dark => #ffffff73
    static var common_icon9_color: CGColor {
        getDynamicColor("common_icon9_color", ["#bbbabbff", "#ffffff73"], UIColor(rgba: "#bbbabbff").cgColor)
    }

    /// Light => #f9f9f9ff, Dark => #202020ff
    static var common_bg32_color: CGColor {
        getDynamicColor("common_bg32_color", ["#f9f9f9ff", "#202020ff"], UIColor(rgba: "#f9f9f9ff").cgColor)
    }

    /// Light => #333333ff, Dark => #ffffffe6
    static var common_icon10_color: CGColor {
        getDynamicColor("common_icon10_color", ["#333333ff", "#ffffffe6"], UIColor(rgba: "#333333ff").cgColor)
    }

    /// Light => #cdcdcdff, Dark => #393939ff
    static var common_icon11_color: CGColor {
        getDynamicColor("common_icon11_color", ["#cdcdcdff", "#393939ff"], UIColor(rgba: "#cdcdcdff").cgColor)
    }

    /// Light => #e6e9eeff, Dark => #27282bff
    static var common_bluishgrey12_color: CGColor {
        getDynamicColor("common_bluishgrey12_color", ["#e6e9eeff", "#27282bff"], UIColor(rgba: "#e6e9eeff").cgColor)
    }

    /// Light => #86898cff, Dark => #bfc5cbff
    static var common_level25_color: CGColor {
        getDynamicColor("common_level25_color", ["#86898cff", "#bfc5cbff"], UIColor(rgba: "#86898cff").cgColor)
    }

    /// Light => #ffede4ff, Dark => #261c14ff
    static var common_orange17_color: CGColor {
        getDynamicColor("common_orange17_color", ["#ffede4ff", "#261c14ff"], UIColor(rgba: "#ffede4ff").cgColor)
    }

    /// Light => #c65228ff, Dark => #ae4e2cff
    static var common_level26_color: CGColor {
        getDynamicColor("common_level26_color", ["#c65228ff", "#ae4e2cff"], UIColor(rgba: "#c65228ff").cgColor)
    }

    /// Light => #f2fefbeb, Dark => #092521e6
    static var common_turquoise12_color: CGColor {
        getDynamicColor("common_turquoise12_color", ["#f2fefbeb", "#092521e6"], UIColor(rgba: "#f2fefbeb").cgColor)
    }

    /// Light => #1cb492ff, Dark => #60dfc8ff
    static var common_turquoise13_color: CGColor {
        getDynamicColor("common_turquoise13_color", ["#1cb492ff", "#60dfc8ff"], UIColor(rgba: "#1cb492ff").cgColor)
    }

    /// Light => #60d2abff, Dark => #00a08aff
    static var common_line15_color: CGColor {
        getDynamicColor("common_line15_color", ["#60d2abff", "#00a08aff"], UIColor(rgba: "#60d2abff").cgColor)
    }

    /// Light => #ff8d65ff, Dark => #d15731ff
    static var common_line16_color: CGColor {
        getDynamicColor("common_line16_color", ["#ff8d65ff", "#d15731ff"], UIColor(rgba: "#ff8d65ff").cgColor)
    }

    /// Light => #ffefebe6, Dark => #4f2a0ce6
    static var common_orange18_color: CGColor {
        getDynamicColor("common_orange18_color", ["#ffefebe6", "#4f2a0ce6"], UIColor(rgba: "#ffefebe6").cgColor)
    }

    /// Light => #fd7443ff, Dark => #fa9875ff
    static var common_orange19_color: CGColor {
        getDynamicColor("common_orange19_color", ["#fd7443ff", "#fa9875ff"], UIColor(rgba: "#fd7443ff").cgColor)
    }

    /// Light => #f7f7f7ff, Dark => #1f1f1fff
    static var common_bg33_color: CGColor {
        getDynamicColor("common_bg33_color", ["#f7f7f7ff", "#1f1f1fff"], UIColor(rgba: "#f7f7f7ff").cgColor)
    }
}