use_frameworks!

platform :ios, '11.0'

workspace './ThemeKit.xcworkspace'

target 'ThemeKit_Example' do
  pod 'ThemeKit', :path => '../'

  target 'ThemeKit_Tests' do
    inherit! :search_paths

    
  end
end

# make sure all targets min deployment valid.
post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
  end
end
